### ISSUE TITLE
What quantity to visualize in height profiles

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#1]
@mrtnrey what quantity do we want to visualize in the bird profiles? By default [`plot(vpts)`](http://adriaandokter.com/bioRad/reference/plot.vpts.html) in bioRad visualizes bird density:

![chart](http://adriaandokter.com/bioRad/reference/plot.vpts-1.png)

I think that's the best one to visualize, as **number of birds/km3** is the easiest to understand - especially compared with reflectivity (dBZ) or BIRDTAM codes - even if it relies on an assumed RCS (radar cross section) of 11.

**Comment by niconoe** [comment]
We currently show density, for the reason stated above.

Is that good enough for now?

**Comment by peterdesmet** [comment]
Yes, for now. At some point we should also show BIRDTAM codes. I'll create a separate issue for this.
