### ISSUE TITLE
Some redundant traffic from data repository?

### ISSUE THREAD

**Issue by mrtnrey** [inbo/crow#101]
It seems the app downloads the vpts files more than once.
E.g. at initial load, it loads the two behel files _four_ times?
![ScreenshotCROWnetwrk](https://user-images.githubusercontent.com/24940236/100624403-b8122180-3323-11eb-8e0c-1e5001642702.png)

**Comment by niconoe** [comment]
Hmmm, that's... interesting 😲  

I'm pretty sure it's a recent bug, but not totally unexpected because of recent heavy refactoring (due to my late discovery of [Vuex](https://vuex.vuejs.org/)) 

Will investigate that soon!

**Comment by niconoe** [comment]
Update: solved some of those issues (on form change and time navigation), but there's still work to be done:

- At initial data load, the operation is still performed three times 
- If the data is displayed as UTC and only for one day can we load one data file instead of two?

**Comment by mrtnrey** [comment]
Thanks Nicolas for looking at this.
It is an important issue since our IT would like to limit the number of allowed parallel downloads (per IP-address) from the data repo. We had some problems in another project in this respect.

**Comment by niconoe** [comment]
The "At initial data load, the operation is still performed three times" point is now solved.

**Comment by niconoe** [comment]
The second point (unnecessary data load for the day before when in UTC mode) is now also solved.

There's now no more redundant traffic that I know of :)
