### ISSUE TITLE
Proofread french translations

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#103]
Hi,

I'm currently in the process of translating CROW into French. That's not a problem for me and I'm a native speaker, but I'd feel more comfortable if another pair of Francophone eyes could proofread it before the app is publicly released. Someone at KMI/IRM maybe, @mrtnrey?

(this is for later, the French translation is not ready yet)

**Comment by mrtnrey** [comment]
Ok, I'll ask a colleague!

**Comment by niconoe** [comment]
That's great Maarten! The translations should be okay, so your colleague can have a look whenever he/she wants.

Comments about the translations (here or by e-mail) are fine, a pull request would also work if your colleague is comfortable with code and GitHub.

**Comment by mrtnrey** [comment]
Waiting for the "total number"-sentence in #112 to aks my colleague to proofread

**Comment by peterdesmet** [comment]
This sentence has now been added and is live. Review of the texts is welcome: https://inbo.github.io/crow/#/

**Comment by mrtnrey** [comment]
_Remarks of my FR colleague below_

songbirds = passereaux ? : à vérifier par un ornitho

Les radars météorologiques détectent la pluie mais aussi les oiseaux présents dans l'atmosphère. Grâce à ces données, les scientifiques peuvent étudier les migrations des oiseaux. Ceci est particulièrement utile pour les passereaux qui migrent la nuit. Grâce aux graphiques ci-dessous vous pouvez visualiser les données provenant de **dix** radars permettant de couvrir le Benelux dans son ensemble.

Veuillez noter que le nombre d'oiseaux est une estimation qui dépend de la configuration du radar et qui peut être incorrecte, en particulier à basse altitude où les échos provenant des oiseaux et du sol sont difficiles à distinguer.

Ce graphique montre la **densité d'oiseaux** en fonction du temps (axe x) et de l'altitude par rapport au niveau de la mer (axe y). La palette de couleurs BirdTAM est conçue pour l'aviation.

Graphique : hauteur --> altitude

Ce graphique montre le **nombre total d'oiseaux** (toutes altitudes confondues) passant à un moment donné. Au total, environ **900 oiseaux** ont survolé un transect de 1 km pendant la période affichée.

Rem. Laurent : ne comprend pas. Où est le transect de 1 km ?

Légende figure :
km carré --> km<sup>2</sup>
RTR surface horaire reflectée --> surface horaire réfléchie par les oiseaux (pas très clair pour moi : est-ce une moyenne horaire de la radar cross section ?)
VIR : surface réfléchie

Données radar fournies par :

Institut Royal Météorologique de Belgique (IRM) (Jabbeke & Wideumont)

**Comment by peterdesmet** [comment]
The suggestions have been added to the website and some charts were further clarified. See live version at https://inbo.github.io/crow/#/
