### ISSUE TITLE
Create navbar component for language selector

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#104]
I think it would be better to move the h1 title and the language selector to a navbar. It also saves on some horizontal space:

<img width="400" src="https://user-images.githubusercontent.com/600993/105210358-384a4b80-5b4b-11eb-94ec-7a891286c0a3.png"><img width="400" src="https://user-images.githubusercontent.com/600993/105210376-3b453c00-5b4b-11eb-9ea9-6f67b524d0b0.png">

@mrtnrey @niconoe what do you think? Do you also prefer the version on the right?

---

@niconoe if, we have a consensus, can you:

- [x] Create a `Navbar.Vue` component
- [x] Link the `LanguageSelector.Vue` from there? Note it should still have an effect on the other components, such as the main app and (eventually) the footer 
- [x] Move the h1 + applied language to that component
- [x] Make "language" translatable

I will then:

- [x] Take care of the styling
- [x] Make the language selector a dropdown

**Comment by peterdesmet** [comment]
Code for me to use later:

```html
<b-navbar type="light">
  <b-container>
    <b-navbar-brand>Birds detected by weather radars</b-navbar-brand>
    <b-navbar-nav class="ml-auto">
      <b-nav-item-dropdown text="Language" right>
        <b-dropdown-item href="#">EN</b-dropdown-item>
        <b-dropdown-item href="#">NL</b-dropdown-item>
        <b-dropdown-item href="#">FR</b-dropdown-item>
      </b-nav-item-dropdown>
    </b-navbar-nav>
  </b-container>
</b-navbar>

.navbar {
  border-bottom: 1px solid #e9ecef;
}
```

**Comment by niconoe** [comment]
Yep, indeed I prefer the version on the right and agree with the list of tasks and responsibilities above!

**Comment by niconoe** [comment]
@peterdesmet: I implemented the first steps. Tell me if you need help turning the buttons into a dropdown. Many thanks!

**Comment by peterdesmet** [comment]
@niconoe this is now implemented, except that the word "language" needs translation abilities:

https://github.com/inbo/crow/blob/2115c8e23af937c60c14e7cb7a1971ea9b3baf48/src/components/LanguageSelector.vue#L2

**Comment by niconoe** [comment]
Done, and already translated!

But I'm wondering if showing the name of the language name itself when the dropdown is collapsed (instead of Language/Taal/Langue) wouldn't be nicer.

**Comment by peterdesmet** [comment]
Yes it would, but wasn't really sure how to do that without repeating it in the dropdown.

**Comment by niconoe** [comment]
@peterdesmet: I changed the code so we the language name itself is used as a title when collapsed, I think it's slightly better. 
What do you think? If you don't like it, we just have to revert 0960539

**Comment by peterdesmet** [comment]
It's excellent.
