### ISSUE TITLE
Create footer component

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#105]
@niconoe can you create a `Footer.vue` component in which I can add all the necessary text. It think that is more elegant that dumping everything in `App.vue` where the footer currently lives. Also, this text should be affected by the selected language.

**Comment by niconoe** [comment]
Yes, will do!

**Comment by niconoe** [comment]
Note: component is called PageFooter to avoid conflicting (in the template) with the [HTML footer tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer).
