### ISSUE TITLE
Use short labelnames to refer to blocks that need translation

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#106]
I noticed that the reference to a block of text is currently the English text itself, e.g. `Note that the bird numbers are estimates`:

https://github.com/inbo/crow/blob/dc19e38118f059d3c7e75eaa303304ce0dd231c6/src/components/Introduction.vue#L39-L43

That means that the English text is maintained in 3 places: 1) as fallback text, 2) as a label, 3) in the translation. If we change one, we have to change all 3, which isn't very DRY. Wouldn't it be better to refer to text blocks with short label names, such as `Note` and just keep the full text in the translation? I'm especially talking about the longer texts, `Interval:` etc. can remain.

The disadvantage is that if a translation is missing, you see the label rather than the English text, but that also stands out more for us developers that something is missing. @niconoe are there other disadvantages?

**Comment by niconoe** [comment]
Nope, I agree and was thinking the same (and actually implemented that in the new `PageFooter` component, because HTML code in labels created more issues). Maybe we can find a middle ground with "half-verbose" label names ('note_that_the_bird_numbers', for example) so the template stays easy to read?

**Comment by peterdesmet** [comment]
Yeah, given that some labels are so short, I would use short English text rather than "code-looking" labels:

```
"Date:"
"Note on numbers"
```

**Comment by niconoe** [comment]
I suggest that we improve (=shorten) those progressively, when working on related code/translations.

**Comment by peterdesmet** [comment]
I have updated/shortened all necessary labels already, see:

https://github.com/inbo/crow/blob/efac7f63b871137ffcae2374085d84c4f042b0d1/src/components/Introduction.vue#L24-L38
