### ISSUE TITLE
App structure

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#107]
`App.vue` currently is:

```html
<template>
  <div id="app">
    <navbar />
    <router-view />
    <page-footer />
  </div>
</template>
```

With `<router-view />` being the `Crow.Vue` template:

```html
<main>
    <Introduction />
    <b-container>visualization itself</b-container>
    <Partners />
</main>
```

@niconoe 

What is the role of the `<router-view />`? Does it have special meaning?

Since all the above are separate components, wouldn't it be better to structure as follows in `App.vue`:

```html
<template>
  <div id="app">
    <navbar />
    <main>
       <Introduction />
       <Crow />
       <Partners />
     </main>
    <page-footer />
  </div>
</template>
```

**Comment by niconoe** [comment]
@peterdesmet : the initial structure was similar to what you suggest, but `<router-view />` has indeed a special meaning. This is populated by [Vue Router](https://router.vuejs.org/) and must hold all the parts that are configurable via the URL, this is for the "share URL" button/feature. 

So I think we have to stick with it, as long as Vue Router is used to implement this feature.

**Comment by peterdesmet** [comment]
Ok, that makes sense, but I still aim remove `<Introduction>` and `<Partners>` from the `<router-view />` ... but let's wait until we have implemented the number in `x birds were detected`.

**Comment by niconoe** [comment]
Well, we use Vue Router here only to be manage parameters to configure a single "page", but its main objective is to allow single page applications where various "pages" dynamically replace the `<router-view />` component. That means that if we move the introduction and partners out and later add a second page such as "About CROW", those components will also appear on the second page.

**Comment by niconoe** [comment]
After some discussion on the chat, I think we can close this for now. Don't hesitate to reopen if I'm mistaken.
