### ISSUE TITLE
Add neighbouring countries to radar map

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#110]
As requested in https://github.com/inbo/crow/issues/97#issuecomment-769738323. I wonder if we can crop a larger svg?

**Comment by niconoe** [comment]
We can obviously look for a solution here, unfortunately the current implementation generates (by applying a geographic projection) the SVG dynamically, based on a GeoJSON file of the country's boundaries. 

I could add the GeoJSON data for France, Netherlands and Germany to the file, but we'll probably have to take some extra measures, such as:

- show the country limits (between the polygons)
- create a zoom mechanism (fit to the existing radars?) so we don't show show half of Europe on a few centimeters, that would be unreadable
- make sure we don't send a too heavy GeoJSON file to visitors

Or maybe the solution is to implement that in a different way (such as a static, hand-made SVG file for the country backgrounds - but we still need to accurately project the radar positions on top of it).

Before jumping to this: @mrtnrey / @peterdesmet : do you already have a more detailed idea of the (visual) result you'd like to see? Thanks!

**Comment by peterdesmet** [comment]
I think we'll either have to hand-crop a bigger svg to one that fits 200x200px or have this be done automatically by the application to the extend of the radars (so you can plug in any svg). The result of both would be the same (extend of radars is used to show map):

<img width="303" alt="Screenshot 2021-02-02 at 11 32 27" src="https://user-images.githubusercontent.com/600993/106588141-bd216600-654a-11eb-964c-bb776d3d9e10.png">

**Comment by mrtnrey** [comment]
Don't make it too complicated; a zoom capability is not needed here. I think a simple extension of the svg as suggested by Peter is sufficient. 

Attached a geoJSON (~100kB) you could use to generate the svg. A simple line is ok, but I won't use red (I'd stick to the blue/grey) colour palette that is used until now.

[geojson_benelx.geojson.zip](https://github.com/inbo/crow/files/5910733/geojson_benelx.geojson.zip)

**Comment by peterdesmet** [comment]
My red was only a quick sketch :smile

**Comment by niconoe** [comment]
solved thanks to @mrtnrey's file and a few small changes! Can you review?

**Comment by peterdesmet** [comment]
Looks great Nico! Leave the issue open so I can review styling.

**Comment by mrtnrey** [comment]
Yes I agree: it already looks great!

I have updated my geojson slightly by adding the IJsselmeer, which was missing in my first version.

_If it's not too much work_, could you take this updated geojson? The Netherlands will look a bit more "familiar".

(low priority though!)

[geojson_benelx.geojson 2.zip](https://github.com/inbo/crow/files/5919310/geojson_benelx.geojson.2.zip)

**Comment by niconoe** [comment]
I updated the GeoJSON, but also improved the logic which was a bit rigid and fragile. The map extent is now dynamically set to match the radars (point) extent, with 15px added padding, that's irrespective of the extent of the countries GeoJSON file. 

Would that work?

**Comment by peterdesmet** [comment]
That sounds great, can you push this to the production site?

**Comment by niconoe** [comment]
Done!

**Comment by peterdesmet** [comment]
Update design so radars stand out more:

<img width="365" alt="Screenshot 2021-02-04 at 16 32 26" src="https://user-images.githubusercontent.com/600993/106915702-9e67ce80-6706-11eb-859c-689e4566a19e.png">

**Comment by mrtnrey** [comment]
:sunglasses: !!!
