### ISSUE TITLE
Language selector improvements

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#111]
- Also share the language via the copy link button
- If no explicit language selection, try to detect via the browser

**Comment by mrtnrey** [comment]
Can we have the language as a key in the URL (I guess this is the first bullet point above) ?

Our final deployment will be on https://www.meteo.be/services/birdDetection/
And three aliases will be defined like this:

https://www.meteo.be/birddetection to https://www.meteo.be/services/birdDetection/?lang=en
https://www.meteo.be/vogeldetectie to https://www.meteo.be/services/birdDetection/?lang=nl
https://www.meteo.be/detectiondoiseaux to https://www.meteo.be/services/birdDetection/?lang=fr

**Comment by peterdesmet** [comment]
Yes, I think it should be possible to do both: just have `?lang=nl` or have it part of the full share link.

**Comment by niconoe** [comment]
This is now implemented, please test!

@mrtnrey : in terms of redirection, take care that a "#" character is part of the URL, and should appear before the parameters:

On my machine (at least, to be checked in your environment): `http://localhost:8080/?lang=fr` gets automatically redirected to `http://localhost:8080/?lang=fr#/` which doesn't work (it should be `http://localhost:8080/#/?lang=nl`)

**Comment by mrtnrey** [comment]
Yes, it seems to work (if you include the # as you mention). Tnx!

I noticed, however, that I have to explicitly reload the whole url (with the browser's reload button) to take effect (changing the lang= key and pressing enter does not work). I don't think that a blocking issue, it just surprised me.

This "#" puzzles me a bit: how come this is necessary?

**Comment by niconoe** [comment]
Yeah, the weird "#" and the "reload not automatic" issues are absolutely linked, this is because we use the [hash mode of Vue-Router](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations).

We previously tried to switch to the more elegant `history mode`, but as explained in the doc above, we need to set-up a catch-all fallback route on the server for that, and that's an option we apparently don't have on GitHub pages, which we currently use for the demo (I guess that's not a problem on KMI's infrastructure, though). So I think our solutions (nothing perfect unfortunately) are:

- live with this "#" symbol
- test the app with "history mode", make the server adjustments and deploy it like that on KMI's server (but the demo would then have a different configuration than the production one, that might lead to "surprises")
- move the demo from GitHub pages to a different host where we have a bit more control over things.

Any thoughts?

**Comment by mrtnrey** [comment]
I didn't expect this complicated story concerning hash mode/history mode.
Personally I don't consider it as an important issue for now: I can live with the "#" !
We should pay attention the [redirection](https://github.com/inbo/crow/issues/111#issuecomment-776063882) is properly working when the webapp is launched.

**Comment by niconoe** [comment]
Thanks @mrtnrey, we agree that accepting to live with the "#" seems the best solution for now!

**Comment by niconoe** [comment]
Reopen because I forgot to implement browser language detection!

**Comment by niconoe** [comment]
That's now implemented, with the following logic:

- If language explicitly set via the URL (share button/or manually added) => use this one
- Otherwise, if the browser preferred language is `nl` or `fr`, use this one
- In other cases, fallback to `en`.

Does that sounds good? Don't hesitate to test!

**Comment by peterdesmet** [comment]
Great, seems to work!
