### ISSUE TITLE
Add Google Analytics?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#114]
Investigate what this means for cookie notification

**Comment by peterdesmet** [comment]
From https://www.datadrivenu.com/gdpr-cookie-consent-google-analytics/ I found:

> If you don't collect personal data, then you don't need to ask for permission to track your visitors anonymously. The key word here is anonymous. If the data your collecting is anonymous and not user-specific, you don't need consent.

That means no cookie warning, which I would prefer over having non-anonymous data. It seems this is a setting in Google Analytics. @mrtnrey can you investigate with KMI if this is something they can set up?

**Comment by mrtnrey** [comment]
I talked to the head of our web section about this, and he's not so favourable of adding Google Analytics to the webapp.
To have some gross statistics on the number of visitors just after the launch, we can get it from the Apache access logs.

If you're fine with this, this issue can be closed.

**Comment by peterdesmet** [comment]
Great!
