### ISSUE TITLE
Add unit to density scale

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#115]
@niconoe I noticed the colour legend is missing a unit. Can you add `birds/km³` to the last tick of the viridis and bioRad legend? Notice also how the bioRad colour legend has no 0 and is cut off.

<img width="744" alt="Screenshot 2021-02-10 at 17 57 20" src="https://user-images.githubusercontent.com/600993/107543379-76c2ab80-6bc9-11eb-98ff-daff5b901568.png">

<img width="742" alt="Screenshot 2021-02-10 at 17 59 10" src="https://user-images.githubusercontent.com/600993/107544083-1ed87480-6bca-11eb-874d-3f5e1a7e8f4b.png">

**Comment by niconoe** [comment]
This is now fixed, I also solved the issue of the tiny black bar at the left of the bioRad scale, and made the scale wider.

**Comment by peterdesmet** [comment]
Is it difficult to have this translatable?

**Comment by niconoe** [comment]
Haha indeed, I forgot about that. Probably not difficult, let me have a look!

**Comment by niconoe** [comment]
Done! (`vogels/km³` is decent Dutch, isn't it?)

**Comment by peterdesmet** [comment]
Great!
