### ISSUE TITLE
Switch charts?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#120]
We're so used to seeing the vpts chart first, because that is how the raw data comes in, while the vpi chart is a more derived product. I wonder though if it doesn't make more sense to show that derived product first, especially for novice users. The vpts chart can the be used to delve further into those results. This might avoid some of the questions mentioned in #119. @robinbrabant @mrtnrey thoughts?

![9f7ace3b-1f33-4f87-bc76-917e2dbb4e31](https://user-images.githubusercontent.com/600993/107695548-1018bd00-6cb1-11eb-89a6-0dd09d0d0936.png)

Essen:

![3af94f54-5e8a-457f-8aff-ef0f0361f96b](https://user-images.githubusercontent.com/600993/107695496-f8413900-6cb0-11eb-82b4-fade9736c6b4.png)

**Comment by mrtnrey** [comment]
The density chart is the first thing I am looking at, but indeed: I am biased.
Your proposition also breaks with how the chart is shown at the Flysafe-website.
Personally I am not very enthusiastic, but it's up to you @peterdesmet 
Maybe you can ask your unprejudiced colleague for advice?

Somehow related (and maybe worth a new question): I am more used to the bioRad scale than the Viridis. Could we make the bioRad the default one?

**Comment by robinbrabant** [comment]
I like the suggestion. For a broader public, the MTR figure is the most understandable. More experienced users can then take a closer look at the density chart to see the altitude birds are flying. So for me, it would indeed be more user friendly to put the MTR first, but I would understand if you would keep the density on top to be uniform with the flysafe site.

**Comment by peterdesmet** [comment]
This is now live.

@mrtnrey if you bookmark the site as https://inbo.github.io/crow/#/?vpColorScheme=biorad it will have your favourite colour scheme 😉  And I guess @hvangasteren might bookmark it as https://inbo.github.io/crow/#/?vpColorScheme=birdtam

**Comment by hvangasteren** [comment]
YES YES J

 

Thanks
