### ISSUE TITLE
Avoid small font for better readability?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#121]
@robinbrabant @mrtnrey I wonder if it wouldn't be better to not have any small font at all. To me it improves readability without taking away from the visuals:

![98cc7519-e4a5-4621-be58-b7fffd992ccf](https://user-images.githubusercontent.com/600993/107696112-d5635480-6cb1-11eb-95ab-db33bbe5c184.png)

vs

![56714445-7fcf-4824-aa93-9c5cfa318304](https://user-images.githubusercontent.com/600993/107696483-4c98e880-6cb2-11eb-8301-1d689a326c56.png)

**Comment by mrtnrey** [comment]
I think you're right about the font.

And this may also apply to the first sentence of the intro ("Weather radars do not only detect precipitation, but also birds in the sky.")

**Comment by peterdesmet** [comment]
As in the first sentence can be regular font as well?

<img width="986" alt="Screenshot 2021-02-12 at 09 06 19" src="https://user-images.githubusercontent.com/600993/107743672-97961880-6d11-11eb-9107-6f33f4167711.png">

**Comment by mrtnrey** [comment]
Yes, it brings more uniformity across the site overall.
I think I prefer this version.

**Comment by robinbrabant** [comment]
I agree. I also prefer the version where all the text has the same font.

**Comment by peterdesmet** [comment]
This is now live.
