### ISSUE TITLE
Limit vpts plots to valid sd_vvp?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#122]
Comment by @mrtnrey in https://github.com/inbo/crow/issues/119#issuecomment-778056067

> The German radars are indeed quite noisy.
We could consider to limit the density plot to the bins that have a valid `sd_vvp`in the vpts-data.
The `sd_vvp` is the final check in the vol2bird algorithm whether the bin is bird-reflectivity or something else.  This should be quite easily implemented&tested. We have then also a better consistency with the MTR-charts.
The drawback is that most plots will be quite empty...

**Comment by niconoe** [comment]
Allright, two related questions:

- what is considered a valid `sd_vvp`?
- what should we do with rows that have an invalid `sd_vvp`? Consider that the density is 0? Consider that's missing data and display in gray? display in another specific (dubious data?) colour?

**Comment by mrtnrey** [comment]
- a value different from "nan"
- I would use grey. It's really "missing" date indeed, but it's certainly not zero too.

**Comment by niconoe** [comment]
Thanks @mrtnrey. It appears the profile integration code filters out data where `sd_vvp` is < 2:(https://github.com/inbo/crow/blob/b56f202c1c4c603f9177f7b160cef5e6afa634c8/src/helpers.ts#L148

I was wondering if we should use the same criteria, so data is more consistent between VTPS and VPI charts?

**Comment by mrtnrey** [comment]
Yes, this is correct. The value sd_vvp is used to make the distinction between birds sd_vvp>2 and rain+insects (sd_vvp<2).
But it seems that everything is shown in the density chart, independent of sd_vvp ?
(I have to say that I do the same for the static images I send to the Airforce: it gives a more complete idea, but it might raise questions for the broad public).

**Comment by peterdesmet** [comment]
Should we make a distinction in doing that for regular vs BirdTAM charts?

**Comment by mrtnrey** [comment]
Hmm, maybe first wait for the effect of this additional sd_vvp filter on the density charts.
An alternative strategy would be to finetune the vol2bird settings for the German radars at KMI. We have some options there
https://github.com/adokter/vol2bird/blob/master/etc/options.conf

**Comment by mrtnrey** [comment]
In my **development-Docker** of vol2bird, I have changed the settings for the two German and two French radars: I have set the REQUIRE_VRAD switch in vol2bird to "TRUE":
https://github.com/adokter/vol2bird/blob/cff8aac3f1f53a955e74a20c009ba07959a4f349/etc/options.conf#L92

The result can be seen on my personal instance of CROW
(example for Essen):
https://ayco.duckdns.org/crow/#/?radar=deess&date=2021-02-16&interval=24&timedisplay=radarLocal&vpiMode=mtr&vpColorScheme=viridis&lang=en
**versus**
https://inbo.github.io/crow/#/?radar=deess&date=2021-02-16&interval=24&timedisplay=radarLocal&vpiMode=mtr&vpColorScheme=viridis&lang=en
(Neuheilenbach is currently not available)

As expected, the density graphs are much cleaner now (even empty...).

The drawback is that there is much less information in the "vpts" files (the "dens" column is now "nan" everywhere).
So it might be preferable to implement this in the visualisation, and not directly in the vol2bird settings.
@peterdesmet what do you think? My proposition is to add a condition on sd_vvp in the code of CROW, and not in the vol2bird. But I'm open to discuss.

**Comment by peterdesmet** [comment]
Let's ask @adokter or @cecilianilsson709: Is it better to use `REQUIRE_VRAD = TRUE` when processing pvol data? And would you do that at the level of processing (and thus reflected in the data) or at the level of visualizing it?

With `REQUIRE_VRAD = TRUE`:

<img width="805" alt="Screenshot 2021-02-16 at 15 32 08" src="https://user-images.githubusercontent.com/600993/108076830-26859680-706c-11eb-9ef8-349787473d76.png">

With default `REQUIRE_VRAD = FALSE`:

<img width="798" alt="Screenshot 2021-02-16 at 15 32 25" src="https://user-images.githubusercontent.com/600993/108076925-3ef5b100-706c-11eb-9eca-65d9d329d216.png">

**Comment by mrtnrey** [comment]
Just for completeness: the `REQUIRE_VRAD = TRUE` takes effect from around 10 CET in the upper graph. From then on, it is almost empty.

**Comment by adokter** [comment]
Hi, REQUIRE_VRAD operates at the pixel level, it throws out pixels that do have a valid reflectivity value but not a valid radial velocity value. The default behaviour is to have REQUIRE_VRAD=False, so all available and valid reflectivity values are included in the calculation of the bird densities.

It was originally implemented for French radars that always delivered a radial velocity value, even for empty airspace and irrespective of the reflectivity value (basically giving noise radial velocity values for airspace with very low or no reflectivity). By requiring that there is a matching radial velocity you can effectively throw out the noise radial velocity values.

The fact that your profile is empty once you enable REQUIRE_VRAD at 10 CET suggests that the reflectivities values do not have a valid corresponding velocity value. That can happenin pixels with very weak signals, or pixels for which a lot of ground clutter has been removed.  Either way the above profile looks quite noisy and the patterns you see are unlikely the result of birds. I'm not seeing a colorscale but are these very weak signals?

**Comment by peterdesmet** [comment]
@adokter here's the same chart in more familiar colours (with new data for the rest of the day). Maximum values seem to be around 50:

<img width="806" alt="Screenshot 2021-02-17 at 09 57 27" src="https://user-images.githubusercontent.com/600993/108180065-9ea09a80-7106-11eb-9964-9f77520bf304.png">

When translated to MTR, we get no data:

<img width="784" alt="Screenshot 2021-02-17 at 09 59 35" src="https://user-images.githubusercontent.com/600993/108180302-e1fb0900-7106-11eb-99ed-8dd90c21dc43.png">

**Comment by mrtnrey** [comment]
Hi & thanks @adokter !
I have to investigate the case of the German radars a bit more in detail (and ask advice to some of my colleagues).
#### 2021-02-13 15:00 UTC
For now, I focussed on one particular timestamp (without any precip in the data, but with strong bird detections which are not realistic).

It seems that the Vrad files of the German radars are strongly filtered and even almost empty, while for all the other radars Vrad is less filtered. On the images below, you'll see the dBuZ (="TH") and Vrad data from the 0.5° elevation for DEESS (100km ppi). While the dBuZ is very noisy, the V image is almost empty... This is not the case for the Be, Nl & Fr radars.

I have also uploaded the HDF files for that particular timestamp (zipped); it would be instructive if one of you could quickly process these files with bioRad. If merged files are needed (TH+V) please let me know.
[deess20210213T1500_hdf.zip](https://github.com/inbo/crow/files/5995896/deess20210213T1500_hdf.zip)

I'll try to contact the German colleagues to see whether they can provide more guidance (e.g. if they have uncorrected V-data available). The processing is not so straightforward though, since DWD is sending slice-by-slice. These slices are then grouped into three files (dBZ, dBuZ and V) by us. For vol2bird, an additional step is needed: the merging into one single hdf file.

```
# vol2bird Vertical Profile of Birds (VPB)
# source: WMO:10410,NOD:deess
# polar volume input: /tmp/20210213150000.rad.deess.pvol.th.sc_vol-5min-ng-01_ess.pvol.h5
# date   time HGHT    u      v       w     ff    dd  sd_vvp gap dbz     eta   dens   DBZH   n   n_dbz n_all n_dbz_all
20210213 1500    0    nan    nan     nan   nan   nan    nan T    nan    nan    nan    nan     0     0     0     0
20210213 1500  200    nan    nan     nan   nan   nan    nan T    nan    nan    nan  49.90     0     0     7  7171
20210213 1500  400    nan    nan     nan   nan   nan    nan T  -8.68   48.4   4.40  40.42     0   116     0  5748
20210213 1500  600    nan    nan     nan   nan   nan    nan T  -4.43  128.7  11.70  12.88     0   646     0  6819
20210213 1500  800    nan    nan     nan   nan   nan    nan T  -6.88   73.1   6.65  10.43     0   955     0  5353
20210213 1500 1000    nan    nan     nan   nan   nan    nan T  -7.03   70.7   6.42   9.69     0  1230     1  5397
20210213 1500 1200    nan    nan     nan   nan   nan    nan T  -8.12   55.0   5.00   8.14     0  1309     0  4662
20210213 1500 1400    nan    nan     nan   nan   nan    nan T  -7.97   56.9   5.17   8.74     0  1138     0  3591
20210213 1500 1600    nan    nan     nan   nan   nan    nan T  -7.28   66.7   6.06   7.39     0  1024     0  3593
20210213 1500 1800    nan    nan     nan   nan   nan    nan T  -6.97   71.6   6.51   9.97     0   847     0  2520
20210213 1500 2000    nan    nan     nan   nan   nan    nan T -10.16   34.4   3.13   5.49     0   883     0  2512
20210213 1500 2200    nan    nan     nan   nan   nan    nan T -10.68   30.5   2.77   3.17     0   847     0  2158
20210213 1500 2400    nan    nan     nan   nan   nan    nan T  -2.44  203.2  18.47   2.04     0   661     0  1777
20210213 1500 2600    nan    nan     nan   nan   nan    nan T  -8.00   56.5   5.14   6.30     0   523     0  1440
20210213 1500 2800    nan    nan     nan   nan   nan    nan T  -6.40   81.8   7.43   3.34     1   498     1  1059
20210213 1500 3000    nan    nan     nan   nan   nan    nan T -12.12   21.9   1.99   6.08     0   298     0   720
20210213 1500 3200    nan    nan     nan   nan   nan    nan T  -9.46   40.4   3.67   2.00     0   939     0  1797
20210213 1500 3400    nan    nan     nan   nan   nan    nan T -11.80   23.6   2.14  -3.26     0   535     0  1080
20210213 1500 3600    nan    nan     nan   nan   nan    nan T  -0.14  345.0  31.37   1.00     0   657     0  1076
20210213 1500 3800    nan    nan     nan   nan   nan    nan T  -6.83   74.0   6.73  -0.94     0   332     0   720
20210213 1500 4000    nan    nan     nan   nan   nan    nan T -10.58   31.2   2.84   3.22     0   321     0   720
20210213 1500 4200    nan    nan     nan   nan   nan    nan T  -7.68   60.9   5.53  -0.54     0   472     0   716
20210213 1500 4400    nan    nan     nan   nan   nan    nan T -10.87   29.2   2.65  -0.16     0   371     0   720
20210213 1500 4600    nan    nan     nan   nan   nan    nan T -10.10   34.8   3.17  -2.62     0   750     0  1080
20210213 1500 4800    nan    nan     nan   nan   nan    nan T  -8.59   49.3   4.48   3.20     0   188     0   360
```

![DEESS_20210213T1500UTC](https://user-images.githubusercontent.com/24940236/108210722-35338280-712c-11eb-8dd4-dd0b39545890.png)

![DEESS_2021021315003501dBuZ](https://user-images.githubusercontent.com/24940236/108209543-b722ac00-712a-11eb-8bea-63a01a4f6901.png)
![DEESS_2021021315003501dBZ](https://user-images.githubusercontent.com/24940236/108209554-ba1d9c80-712a-11eb-86b7-2e8ef46c6d15.png)
![DEESS_2021021315003501V](https://user-images.githubusercontent.com/24940236/108209557-bab63300-712a-11eb-8499-70a78815651c.png)

**Comment by adokter** [comment]
> When translated to MTR, we get no data:

Yes that makes sense, MTR is effectively reflectivity x speed, and since there are no valid speed estimates nothing will show up.

**Comment by adokter** [comment]
Hey @mrtnrey, it's a major problem that OPERA policies have changed to exchange cleaned data, and that nicely Doppler-filtered reflectivity data that includes biology is becoming less available. It might be that your VRADH is for cleaned data in which all biology has been removed by dual-polarization filters. You could verify if UVRADH is available, which is the uncleaned version of VRADH, however vol2bird needs to be updated to be able to use a different radial velocity quantity than VRADH (added an issue here https://github.com/adokter/vol2bird/issues/176)

Looking at above reflectivity image for TH it shows a lot of ground clutter, and I think this is responsible for the steady horizontal stripes in your profile

Some radars provide clutter correction values CCORH and you could reconstruct an uncleaned DBZH from TH+CCORH - this isn't an option in vol2bird yet, but I've been wanting to add this (just added issue here https://github.com/adokter/vol2bird/issues/175)

You might also consider only visualizing vertical profile data that has both bird density and speed, as bird signals are expected have both, as another way of not showing this static clutter background

**Comment by adokter** [comment]
you may also want to check in with @bart1 at University of Amsterdam, they have been working on the German data recently as well

**Comment by adokter** [comment]
For deess20210213T1500_hdf.zip it would be helpful if you could provide a merged polar volume, vol2bird still requires all scan parameters to be available in a single volume

**Comment by bart1** [comment]
@adokter & @mrtnrey  I do not have experience with calculating vps from data obtained through opera. All data at the UvA has been obtained directly from DWD. @BerendWijers did the file merging for that. The results are generally good.

**Comment by mrtnrey** [comment]
Hi @bart1, we receive our files for this project also directly from DWD, not Opera. Currently we receive DBZH (strongly filtered), VRAD (strongly filtered) and TH (very noisy).

@adokter here is the merged file:
[20210213150000.rad.deess.pvol.th+vrad.pvol.h5.zip](https://github.com/inbo/crow/files/5997056/20210213150000.rad.deess.pvol.th%2Bvrad.pvol.h5.zip)

The request to receive unfiltered-V is just sent to DWD this afternoon. But as I understand, vol2bird is not capable (yet) of ingesting such a **u**VRAD?

I guess for the time being we should confine the density charts to `sd_vvp` to valid (non-nan) and `>2` (the visualisation tool we are building is also for the broad public), but keeping it in the vpts-files. This is implicitly your suggestion in 
> You might also consider only visualizing vertical profile data that has both bird density and speed, as bird signals are expected have both, as another way of not showing this static clutter background

no?
Thank you guys for the advice.

**Comment by bart1** [comment]
It might also be worth talking to the vogelwarte helgoland as they have been handling recent German weather data. I tend to remember they had some issues as well although I do not know the exact details but they have also been retrieving data.

**Comment by adokter** [comment]
Hi @mrtnrey, this is what I get for the merged file you uploaded [here](https://github.com/inbo/crow/issues/122#issuecomment-780677259) with the latest version of vol2bird (0.5.0.9174):
```
Loaded user configuration file 'options.conf' ...
Warning: no dual-pol moments found, switching to SINGLE POL mode
Warning: Nyquist interval attribute not found for scan 1, using radial velocity offset (32.1 m/s) instead 
Warning: Nyquist interval attribute not found for scan 2, using radial velocity offset (32.1 m/s) instead 
Warning: Nyquist interval attribute not found for scan 3, using radial velocity offset (32.1 m/s) instead 
Warning: Nyquist interval attribute not found for scan 4, using radial velocity offset (32.1 m/s) instead 
Warning: Nyquist interval attribute not found for scan 5, using radial velocity offset (32.1 m/s) instead 
Warning: Nyquist interval attribute not found for scan 6, using radial velocity offset (32.1 m/s) instead 
Warning: Nyquist interval attribute not found for scan 7, using radial velocity offset (32.1 m/s) instead 
Warning: Nyquist interval attribute not found for scan 8, using radial velocity offset (32.3 m/s) instead 
Warning: Nyquist interval attribute not found for scan 9, using radial velocity offset (32.3 m/s) instead 
Warning: Nyquist interval attribute not found for scan 10, using radial velocity offset (32.3 m/s) instead 
# vol2bird Vertical Profile of Birds (VPB)
# source: WMO:10410,NOD:deess
# polar volume input: 20210213150000.rad.deess.pvol.th+vrad.pvol.h5
# date   time HGHT    u      v       w     ff    dd  sd_vvp gap dbz     eta   dens   DBZH   n   n_dbz n_all n_dbz_all
20210213 1500    0    nan    nan     nan   nan   nan    nan T    nan    nan    nan    nan     0     0     0     0
20210213 1500  200    nan    nan     nan   nan   nan    nan T    nan    nan    nan  49.90     0     0     7  7171
20210213 1500  400    nan    nan     nan   nan   nan    nan T  -6.95   72.0   6.55  42.30     0   563     7  9344
20210213 1500  600    nan    nan     nan   nan   nan    nan T  -4.43  128.7  11.70  12.88     0   646     0  6819
20210213 1500  800    nan    nan     nan   nan   nan    nan T  -7.31   66.3   6.03  13.18     0  1565     0  6793
20210213 1500 1000    nan    nan     nan   nan   nan    nan T  -7.82   59.0   5.36   8.96     0  2509     1  7557
20210213 1500 1200    nan    nan     nan   nan   nan    nan T  -8.74   47.6   4.33   7.59     0  1644     0  5382
20210213 1500 1400    nan    nan     nan   nan   nan    nan T  -4.43  128.6  11.69  10.48     0  1946     0  5031
20210213 1500 1600    nan    nan     nan   nan   nan    nan T  -9.35   41.4   3.77   5.95     0  2119     0  5393
20210213 1500 1800    nan    nan     nan   nan   nan    nan T  -3.97  143.1  13.01  11.52     0  1457     0  3600
20210213 1500 2000    nan    nan     nan   nan   nan    nan T  -6.62   77.7   7.06   5.03     0  1648     0  3592
20210213 1500 2200    nan    nan     nan   nan   nan    nan T  -4.99  113.1  10.28   7.99     0  2191     0  4318
20210213 1500 2400    nan    nan     nan   nan   nan    nan T  -4.08  139.3  12.66   3.37     0  1075     0  2497
20210213 1500 2600    nan    nan     nan   nan   nan    nan T  -7.87   58.2   5.29   4.43     0  1642     0  3240
20210213 1500 2800    nan    nan     nan   nan   nan    nan T  -2.93  181.8  16.53   4.97     1  1475     1  2499
20210213 1500 3000    nan    nan     nan   nan   nan    nan T  -5.06  111.3  10.12   4.14     0   869     0  1440
20210213 1500 3200    nan    nan     nan   nan   nan    nan T  -8.86   46.4   4.22   0.97     0  1515     0  2517
20210213 1500 3400    nan    nan     nan   nan   nan    nan T -11.68   24.2   2.20  -4.84     0  1139     0  1800
20210213 1500 3600    nan    nan     nan   nan   nan    nan T  -1.30  264.2  24.02   0.17     0   886     0  1436
20210213 1500 3800    nan    nan     nan   nan   nan    nan T  -8.58   49.5   4.50  -2.34     0   578     0  1080
20210213 1500 4000    nan    nan     nan   nan   nan    nan T  -2.76  188.8  17.16   8.95     0   832     0  1440
20210213 1500 4200    nan    nan     nan   nan   nan    nan T  -6.36   82.5   7.50  -0.94     0   741     0  1076
20210213 1500 4400    nan    nan     nan   nan   nan    nan T  -4.95  114.2  10.38   0.25     0   641     0  1080
20210213 1500 4600    nan    nan     nan   nan   nan    nan T  -9.22   42.7   3.88  -2.83     0  1307     0  1800
20210213 1500 4800    nan    nan     nan   nan   nan    nan T -10.16   34.4   3.12   0.35     0   474     0   720
```
Because you only have TH and not DBZH, I had to specify `DBZTYPE=TH` in vol2bird's options file (`options.conf`)

**Comment by mrtnrey** [comment]
Some quantitative differences are seen indeed. For my vol2bird docker in the back-end, I am using an offline, forked version of vol2bird, which dates from 11 Jun, 2020. It's too risky to update vol2bird so close before the launch of CROW inho. But the newest vol2bird version will still show quite high values for the German radars anyway (so this will not solve the problem of the noisy German radars). A more profound solution would be to add a static clutter map for these radars (not implemented right now).

@niconoe I think we should go for the filter on `sd_vvp` to valid (i.e. non-`nan` and `>2`)

**Comment by niconoe** [comment]
@mrtnrey / @peterdesmet: I now implemented the filtering. That seems to work well for the German radars, but quite a bit of data is also filtered from other radars:

<img width="787" alt="Screenshot 2021-02-23 at 09 31 37" src="https://user-images.githubusercontent.com/386387/108818958-73142900-75ba-11eb-83c8-062c1e84fb8f.png">

Any opinion about that? I guess it's a good thing in terms of data, in terms of aesthetics I wonder if we shouldn't use another colour (or just a lighter gray?) for "no data".

**Comment by niconoe** [comment]
As a side effect, this change is excellent for the application performance ;)

**Comment by mrtnrey** [comment]
This was to be expected. It is for sure more scientific in any case.
Yes, a lighter color is a good idea!

**Comment by peterdesmet** [comment]
@niconoe you can try `#C0C0C0`

**Comment by niconoe** [comment]
Done (there's already a `VPChartStyle.noDataColor` variable in `config.ts`, for easy configuration).
