### ISSUE TITLE
Include how to cite?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#123]
Notice suggested citation at bottom of https://birdcast.info/migration-tools/migration-forecast-maps/ I think it might be worth to include this for CROW, at least in the README of the repo.

**Comment by mrtnrey** [comment]
Yes I agree, but how would this citation would look like? (we don't have a paper describing CROW).

**Comment by peterdesmet** [comment]
We don't need to have a paper, one can also reference the visualization itself. Something along the lines of:

> Noé N, Reyniers M, Van Hoey S, Desmet P (2021) CROW: visualization of birds detected by weather radars. https://inbo.github.io/crow/ [access date]

**Comment by peterdesmet** [comment]
The citation is now included near the top of the fully reviewed README: https://github.com/inbo/crow#readme
