### ISSUE TITLE
Meteo.be deployment checklist

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#125]
To check before we publicly spread the word:

- [ ] Create release
- [ ] All the redirection (per-language URLs, ...) are working properly

(to be continued)

**Comment by mrtnrey** [comment]
Hi @niconoe, please could you inform me explicitly when the app is ready for final deployment on meteo.be (then I can ask our web team to do it). Tnx!

**Comment by niconoe** [comment]
Hi @mrtnrey!

According to the milestone (https://github.com/inbo/crow/milestone/1), it could be considered ready. That being said:

- If you think some other features are urgently needed for v1, shout and I'll do my best (it also depends on your deadlines!)
- if not, it would be great if we all try once again to try every feature, looking for newly introduced bugs

any opinion? Also @peterdesmet? @robinbrabant?

**Comment by peterdesmet** [comment]
Not detecting the language based on browser will affect a lot of users, so if possible I would implement that one before deployment.

**Comment by niconoe** [comment]
Sorry I was unclear @peter: language detection is done, I just let the issue open so you can read about the solution and test on your side (quite important since we use different browsers / settings, and standardization is poor on this topic).

**Comment by peterdesmet** [comment]
Great, seems to work!
