### ISSUE TITLE
Update link to data on CROW metadata page

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#127]
@mrtney under what license are the data released on https://opendata.meteo.be/ or specifically https://opendata.meteo.be/ftp/observations/radar/vbird/ ? I could not find that information.

If you still have to adopt one, I recommend using https://creativecommons.org/publicdomain/zero/1.0/ It is also used for vp(ts) data in the ENRAM data repository.

**Comment by mrtnrey** [comment]
Hi @peterdesmet the information about the licence is available in our catalogue
https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_CROW
It is CC Attribution (CC BY 4.0).

**Comment by peterdesmet** [comment]
Hmm, from our footer it might be better then to link that page, as it provides metadata and a license. But if we do that, it would be good if under "Downloads and links":

https://opendata.meteo.be/

Is replaced by

https://opendata.meteo.be/ftp/observations/radar/vbird/

**Comment by mrtnrey** [comment]
Yes, linking to https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_CROW is probably more offical. This page provides the "official" data description for the INSPIRE catalogue of RMI metadata.
Note that the content of this page is automatically included in the federal data portal data.gov.be too: 
https://data.gov.be/en/dataset/rmidatasetcrow
(sidenote:  I see that the "pure" ftp link is still given there; I can ask to change this into the https link).

**Comment by peterdesmet** [comment]
@mrtnrey the "pure" FTP link is actually quite useful, so I would leave that one be. The one I would update is:

> RMI opendata portal
> https://opendata.meteo.be -> https://opendata.meteo.be/ftp/observations/radar/vbird/

**Comment by mrtnrey** [comment]
Hi @peterdesmet the link is added. See https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_CROW

(Our IT dept wanted to keep _also_ the original link, since it is is in all datasets : the global portal will contain informations about the licenses, documentation, etc ...)
