### ISSUE TITLE
Day/night not updated for 3 days in Chrome

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#132]
Funny we never noticed it in the press screenshot, but the day/night shading is off:

<img width="730" alt="Screenshot 2021-03-22 at 11 15 05" src="https://user-images.githubusercontent.com/600993/111974619-dfbe0d00-8aff-11eb-8b2a-ae9bfd7cc86d.png">

It should be:

<img width="722" alt="Screenshot 2021-03-22 at 11 15 39" src="https://user-images.githubusercontent.com/600993/111974697-fc5a4500-8aff-11eb-849f-fe47042ce215.png">

I have encountered it before this morning, but can't replicate it anymore. Maybe a caching issue?

**Comment by peterdesmet** [comment]
Ah, here's how I can replicate it:

1. Go to https://www.meteo.be/services/birdDetection/#/
2. Update date to `21/02/2021`
3. Change to `3d`

**Comment by niconoe** [comment]
Solved! For the record, it was actually due only when the month was changed manually, because the date was temporarily invalid (month == '00'), which broke the data flow and gave subsequent issues.
