### ISSUE TITLE
parseVtps reads csv 

### ISSUE THREAD

**Issue by baptischmi** [inbo/crow#135]
I need to combine the daily vpts using bioRad. Exporting the vpts as fixed-width flat table is probably feasible. Alternatively, _CROW_ could read csv: https://github.com/inbo/crow/blob/242bbd5cb8a8c64b0fd3c886b7ef4dc1ba21da10/src/helpers.ts#L91-L109

@niconoe : How would you rewrite parseVpts to read csv-files?

**Comment by niconoe** [comment]
@baptischmi : I'm not sure I understand your exact use-case, but indeed it wouldn't be a problem to update/replace that `parseVtps` function to deal with CSV files. I think I heard there will be (or already is?) an effort to define a proper CSV-based standard for VTPS data.

 As soon as we have a a clear definition (ideally with a concrete CSV sample file), I can adapt CROW's code to deal with id!

**Comment by baptischmi** [comment]
@niconoe : thank you. However, the standard CSV is in [discussion ](https://github.com/enram/vpts) for a while... But do you really need the CSV standard if only using seven variables (columns)? Adjusting the column name may be a quick fix.

Let me know if you need a sample CSV-file.

**Comment by peterdesmet** [comment]
@niconoe In general I would agree that we need the standard first, but @baptischmi has a use case where he would have to convert csv to fixed-width, which seems like going in the wrong direction. If you would know and can provide the base functionality of a function reading csv natively, that would help @baptischmi already.

**Comment by niconoe** [comment]
Perfect, I'll do. @baptischmi, can you indeed give me a sample file?

**Comment by baptischmi** [comment]
Thank you @niconoe 
Here is a vpts from chalb 20200920. Produced using bioRad::as.data.frame(my_vpts, , quantities = "dens", suntime = TRUE) -  packageVersion("bioRad") > ‘0.5.2’.

[chalb_vpts_20200920.zip](https://github.com/inbo/crow/files/6348855/chalb_vpts_20200920.zip)

**Comment by niconoe** [comment]
Thanks @baptischmi, I'll make adjustments to CROW so it can read this sample file. A few questions just to do it as efficiently as possible:

- Where will you use/run CROW for that? Will you deploy your own CROW instance to a server (in addition to the two already running instances at https://inbo.github.io/crow/#/ and https://www.meteo.be/services/birdDetection/#/)? If so, I will help you to configure that.
- Please note that currently, CROWs consumes those VTPS data files directly from an HTTP/HTTPS server. So you'll need to upload those data files somewhere before you can visualise them. Is that possible, or should we also adapt CROW for other situations?
- About the file format: 
   - will the order of fields be always the same? 
   - or is it better to infer the field position from the header row (but in that case, we'll always need a header row, with consistent col names
   - to be consistent with the other load function, I'll consume the datetime, height, dd, ff, dens, sd_vvp and eta data. So all other columns will be ignored. I guess that's fine?

**Comment by baptischmi** [comment]
Thanks @niconoe 
i will use/run CROW on a new instance, uploading the vpts on a separate http-server (@peterdesmet already gave me some hints to adjust the config-file). 
File format:
- Response depends on future changes of BioRad: the order and field name may change. I would suggest to change infer the field position from the header row (would only require to adjust the field name, order beeing equal). Do i get this correctly? maybe @peterdesmet has a better response on this.
- yes, you can ignore the other columns. I only want to replicate the existing CROW app.

**Comment by niconoe** [comment]
Perfect! I'm currently working on this. The config file format file will change a bit for more flexibility related to those changes (each radar has its own server URL, file format, ...). I can also help you getting started!

**Comment by niconoe** [comment]
@baptischmi: are the datetimes in the CSV files in UTC?

**Comment by baptischmi** [comment]
Yes, time in UTC.
Thank you for your offer. I will get to you once the http-server is populated with data - hopefully next week.

**Comment by niconoe** [comment]
@baptischmi : I've made good progress on this, but can't really test/finish since there isn't much visible data in the sample file above (all densities are 0 or NA, same for `ff` and `eta` fields, ...).

Do you have a file at hand with data that could be directly visualized? Thanks! 🙏

**Comment by baptischmi** [comment]
The http-server is not ready, so i have attached a zip file with a month of data. 2020 seem to be corrupted at some point.
[chalb.zip](https://github.com/inbo/crow/files/6382569/chalb.zip)

**Comment by baptischmi** [comment]
this should work:
https://opendata.vogelwarte.ch/ftp/observations/radar/wr/bird.vpts/chalb/2019/chalb_vpts_20191020.csv
There are more csv in this directory, but i guess the CROW need to know what files are available on the server to fetch them, correct? The directories are hidden so far.

**Comment by niconoe** [comment]
Thanks @baptischmi!

I think we're almost there, but there is still a little adjustment to be made to the HTTP server: CORS headers should be set so the files can be served to a different (than `opendata.vogelwarte.ch`) domain.

I think you're using Apache? If so, the directive would be: `Header add Access-Control-Allow-Origin *;`. More explanations and examples: https://ubiq.co/tech-blog/enable-cors-apache-web-server/

**Comment by baptischmi** [comment]
Hi @niconoe - thank you for the suggestion. We have added a .htaccess file in the ~/bird.vpts directory:
_Header add Access-Control-Allow-Origin *;_
Can you test? i don't understand how to use test-cors.org: https://www.test-cors.org/#?client_method=HEAD&client_credentials=false&server_url=https%3A%2F%2Fopendata.vogelwarte.ch%2Fftp%2Fobservations%2Fradar%2Fwr%2Fbird.vpts%2F&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

**Comment by niconoe** [comment]
Thanks, I still got an error, but slightly different, I think there might be a typo in the .htaccess: The 'Access-Control-Allow-Origin' header contains multiple values '*;, *', but only one is allowed.

So apparently the server answers `*;, *` while we'd need: `*`

**Comment by niconoe** [comment]
Can you try with just

```
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Methods: "GET,POST,OPTIONS,DELETE,PUT"
```

in the .htaccess file?

**Comment by niconoe** [comment]
Update: I think I'm now good with all necessary background changes (CSV format support, URL configurable per radar, available heights configurable per radar, ...). See example below:

![Screenshot 2021-05-04 at 10 25 22](https://user-images.githubusercontent.com/386387/116978222-b62dff00-acc3-11eb-983b-c08760a3f5fc.png)

Comments:

- This work has been pushed to a [new branch](https://github.com/inbo/crow/tree/more_radars_and_formats)
- It appears the CORS headers are still not working on the `opendata.vogelwarte.ch` server, so the development has been made with a local test server. We'll put that on hold until mid-May after @baptischmi is back from holidays.
- More polishing might be needed after we test this in real-world conditions
- Once things get stabilised, I'll merge changes into the main branch and possibly create a new release.

**Comment by peterdesmet** [comment]
Nice!

**Comment by baptischmi** [comment]
nice! thanks a lot @niconoe. i will solve the issue with the opendata.vogelwarte.ch server asap.
