### ISSUE TITLE
Option to show BIRDTAM codes

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#16]
@mrtnrey should we offer the possibility to show BIRDTAM codes in height profiles (translated from density), so these are more useful to the military?

**Comment by peterdesmet** [comment]
Note by @niconoe in #34:

> ! the scale is fixed, and not dynamic (according to the data range) as the current system.

**Comment by mrtnrey** [comment]
Showing the BIRDTAM codes would be a nice-to-have since the Airforce are heavy users of the profiles.

**Comment by peterdesmet** [comment]
@mrtnrey Ok, do you have a translation table for densities to BIRDTAM codes?

**Comment by niconoe** [comment]
UPDATE: Think I found the info to implement BIRDTAM:

- http://www.flysafe-birdtam.eu/composite_track.php
- http://www.flysafe-birdtam.eu/profile.php?radar=jabbeke

**Comment by mrtnrey** [comment]
@niconoe I don't have the thresholds either.
Do you want me to ask this info to the FlySafe people?

**Comment by niconoe** [comment]
@mrtnrey : that would be amazing!

**Comment by mrtnrey** [comment]
Answer from Hans van Gasteren (Dutch Airforce):

RGB codes van  0-4 in licht groen. BIRDTAM 5 is 100% groen en daarna 6 en hoger. Ik heb ook BIRDTAM 9 geintroduceerd om de extremen (en regen) weer te geven. Zo staan ze althans op dit moment op de FlySafe-pagina en in ons artikel

 BIRDTAM RGB-kleuren = [1 1 1; .9 1 .9; .8 1 .8; .7 1 .7; .6 1 .6; 0 1 0; 1 1 0; 1 .7 .7; 1 0 0; .2 .2 .2;];

**Vanuit dichtheid (#/km^3) naar BIRDTAM:    densitybirdtam = 1.4427.*log(density+1)+1.6781
En dan de getallen naar beneden afronden om de juiste BIRDTAM te vinden: floor(densitybirdtam), (birdtam 5,6 wordt dus een 5!)**

 Overigens voor de vertical integrated densities (VID) gebruik ik dezelfde conversie. density == VID

**Comment by niconoe** [comment]
BIRDTAM colors can now be selected for VP chart.

We'll need some (automated?) data checks to ensure the colors are indeed correct.

**Comment by niconoe** [comment]
Note to self: reimplement using a (D3) quantize scale?
