### ISSUE TITLE
Latest data not available?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#160]
When going to the homepage of CROW (https://www.meteo.be/services/birdDetection/#/?lang=en), no data are loaded:

```
Access to XMLHttpRequest at 'https://opendata.meteo.be/ftp/observations/radar/vbird/behel/2022/behel_vpts_20220624.txt' from origin 'https://www.meteo.be' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Indeed, there are no data uploaded for 20220624 at https://opendata.meteo.be/ftp/observations/radar/vbird/behel/2022/

```
...
behel_vpts_20220622.txt
behel_vpts_20220623.txt
```

@mrtnrey is there a delay in producing these data?

**Comment by mrtnrey** [comment]
No worries: Helchteren is temporarily out of service since 2022-06-23 23:45 UTC. It will be fixed after the weekend (telecom problem). Wideumont is currently being renewed (upgrade to dual-pol). It will be back online in the coming weeks.
