### ISSUE TITLE
User can navigate to the future with the +1/+3 buttons

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/crow#173]
Whereas the datetime picker blocks choosing a future datetime, a user can request future-dates by pushing the +1 button next to the datetime field.

**Comment by peterdesmet** [comment]
I wouldn’t prevent that, since users can also craft a querystring to a future date or non-existent radar. Radar, user should be warned. Imo this can be the same error message as #172

**Comment by stijnvanhoey** [comment]
ok, adding this to #172 to have an alert as if you request an unexisting.
