### ISSUE TITLE
`No data found` shown with data

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#194]
@niconoe any idea what is going on [here](https://crow.aloftdata.eu/#/?radar=nohur&date=2023-03-14&interval=24&timedisplay=radarLocal&vpiMode=mtr&vpColorScheme=viridis&lang=en)? Looks like the `No data found` display is not hidden as it is supposed to be.

<img width="843" alt="Screenshot 2023-04-27 at 15 41 27" src="https://user-images.githubusercontent.com/600993/234880348-c5454435-b171-45a3-bc3a-cdf442dfe785.png">

The chart displays data for 14/03/2023. There is no file for 15/03/2023.

**Comment by niconoe** [comment]
Woops! will investigate.

**Comment by niconoe** [comment]
Note to self. Issue investigated, this is an edge case: in that specific case. `yMaxVal` is 50, so the first part of the condition is true in https://github.com/inbo/crow/blob/e35c0226d3444cb3d8537986250a298682660448/src/components/VPIChart.vue#L387-L388 while there is actually real data.

Solution would be a cleaner way to check that the data passed in props is actually empty. Check all values are NaN? Or 0? Both? to try.

**Comment by niconoe** [comment]
There seems to be cases where the message appears without seemingly any value near 50: https://crow.aloftdata.eu/#/?radar=frnan&date=2023-08-30&interval=24&timedisplay=radarLocal&vpiMode=mtr&vpColorScheme=viridis&lang=en

=> to re-investigate!

**Comment by peterdesmet** [comment]
Also to test https://crow.aloftdata.eu/#/?radar=bejab&date=2019-03-15&interval=72&timedisplay=UTC&vpiMode=mtr&vpColorScheme=viridis&lang=en

**Comment by peterdesmet** [comment]
Deployed on https://crow.aloftdata.eu/ and I can confirm that the two links shared above now show data.
