### ISSUE TITLE
Show radar and code in dropdown

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#195]
@niconoe I want to adapt the dropdown and map to show the `code - location` combination rather than just `location`:

<img width="342" alt="Screenshot 2023-05-10 at 16 22 02" src="https://github.com/inbo/crow/assets/600993/98e9cd51-5cc3-4f92-bea9-f0bda3f9784d">

Code =`odimCode`, location = `text` in `config.ts`, so it should be possible to create a computed value (e.g. `radarLabel`) from the two. I tried to see where it could be introduced, but I got a bit lost in the code. 😅. Is it possible to do that for dropdown and map only? Or do we have to update all `text` properties in `config.ts`, which would not be DRY, is prone to error and would also affect the `selectedRadarLocation` value.

The default value for `radarLabel` could be `text` (keeping with the current value used by RMI crow). For aloft/crow I would use the longer value.

**Comment by niconoe** [comment]
Sounds doable, I'll have a look!

**Comment by peterdesmet** [comment]
Resolved in #196 and #197
