### ISSUE TITLE
Hide historical radars in map

### ISSUE THREAD

**Issue by CeciliaNilsson709** [inbo/crow#201]
Since some sites have had their radar codes updated, some locations have two sets of data associated with them; one "historical" and one active. In the drop down menu both are visible which is great, but in the map there can of course only be one dot per location. 

Currently some dots link to the active radar and some to the historical one. @niconoe Would it be possible to hide the historical ones from the map so that when you click on a location you always see data from the active radar at that site?

**Comment by niconoe** [comment]
Hi @CeciliaNilsson709, yep that's a very reasonable request and - without looking at the code - that doesn't seem too frightening :) I guess I'll also have to update the config file(s) to mark which radars are historical. But that info seems pretty clear in this commit (https://github.com/enram/crow/commit/a1c3d11450a74a0766b814ec7f5ec88f00a547a6) , thanks to the updated labels.

I'll have a look soonish, feel free to ping me if I forget :)

**Comment by CeciliaNilsson709** [comment]
Sounds great, thanks!

**Comment by niconoe** [comment]
PR ready for review!

**Comment by peterdesmet** [comment]
This has been resolved in #202 and pushed to https://crow.aloftdata.eu/ (e.g. `sekkr` no longer covers `sekaa`).
