### ISSUE TITLE
Odd connecting lines in VPI chart

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#21]
See:

<img width="1096" alt="Screenshot 2019-12-18 at 12 05 48" src="https://user-images.githubusercontent.com/600993/71081090-cb69c280-218e-11ea-97f7-3369585a8d1c.png">

**Comment by niconoe** [comment]
@peterdesmet : It also happened to me, but rarely :) 

So don't hesitate to report the exact form parameters next time you see it, so I can reproduce the bug.

**Comment by peterdesmet** [comment]
Not sure how I can reproduce it, but here's another one:

<img width="1126" alt="Screenshot 2020-01-15 at 11 48 49" src="https://user-images.githubusercontent.com/600993/72429885-33f98e80-3791-11ea-9b72-84b32d1fe21a.png">

**Comment by niconoe** [comment]
Okay thanks! Next time, just report the radar and day selected!

**Comment by niconoe** [comment]
We might have solved the problem indirectly (by properly resetting the data between iterations). Please report (with the parameters used) if that happens again, otherwise I'll close this issue in a couple of weeks.

**Comment by peterdesmet** [comment]
Has this been deployed?

**Comment by niconoe** [comment]
Yes

**Comment by niconoe** [comment]
Probably solved during refactoring and code improvements. Please reopen if the issue comes back.
