### ISSUE TITLE
Use date + interval, rather than start/end date

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#22]
Rather than having a start/end date in the application, we should have a single date + interval. This allows:

- The user to more easily walk through time (only one form field to update)
- The application to remain responsive (don't allow to render one year of data)

**Comment by peterdesmet** [comment]
For now I would use a fixed interval (at front-end level: so no option to select it) and follow the [flysafe](http://www.flysafe-birdtam.eu/profiles.php) approach and display 48h of data:

E.g. for date 2019-12-18, **center the chart around UTC noon** (`2019-12-18 12:00 UTC`) and display 24h before and after, which is pulling 3 date files:

- `2019-12-17`: display 12h: 12:00 to 00:00
- `2019-12-18`: display 24h: 00:00 to 00:00
- `2019-12-19`: display 12h: 00:00 to 12:00

<img width="704" alt="Screenshot 2019-12-18 at 12 10 57" src="https://user-images.githubusercontent.com/600993/71081663-f4d71e00-218f-11ea-8e70-402e24c4881a.png">

I also like displaying a vertical gridline for midnight only (see bottom chart).

**Comment by peterdesmet** [comment]
I'm also curious to see a 96h view (5 files)

**Comment by niconoe** [comment]
Just implemented a first version of this. 

With the current implementation, perfs are quite bad with the 96 hours interval.

**Comment by niconoe** [comment]
Let's close this and open specific issues when improvements are needed.
