### ISSUE TITLE
Explore option to bind to canvas rather than svg to improve performance

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#23]
See e.g. https://www.freecodecamp.org/news/d3-and-canvas-in-3-steps-8505c8b27444/

**Comment by niconoe** [comment]
Let's do first a quick investigation to learn:

- in the current implementation, where is most of the time spent (rendering? getting data files? parsing them?) 
- in our specific case, what can we expect to gain if we reimplement with canvas?
- How difficult would that be?

**Comment by niconoe** [comment]
Parking for now since it's currently not needed and will make the whole thing much more complex.
