### ISSUE TITLE
Add smooth transitions when data is updated

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#24]
Nice to have, but I would implement at a later stage, because:

- it will probably make the code much more heavy and complex (D3's is quite low level, and we'll have to implement multiple cases: data added before, after, or replacing the current data, removing data, missing data, updating axis and heatmap colors when the range change, ...)

- there are performance considerations, especially for the Vtps heatmap. Might be mitigated thanks to #23 .

- (given the two points above): It'll look nicer, but otherwise brings little added value

**Comment by niconoe** [comment]
I just implemented smooth "vertical" transitions for VPI data.

For future references: changes in:  
- https://github.com/inbo/crow/commit/6f0bb963052dc728aa9fb85e85b6ab204169ab24
- https://github.com/inbo/crow/commit/9e4f70958acad2c1c85f846bd883f3fb2c7738b3
- https://github.com/inbo/crow/commit/241a200a01c2a7f17762b2d44800235b1d936c60

Lessons learned: looks nice, works, but don't underestimate the impact on code complexity (situation might be improved by extracting the transition to its own component, such as suggested in https://vuejs.org/v2/guide/transitioning-state.html#Organizing-Transitions-into-Components) and performances.

**Comment by peterdesmet** [comment]
Are those smooth transitions now online and how can I test them?

**Comment by niconoe** [comment]
The VPI line on the second chart moves vertically (when initially loading the page, and when changing the displayed variable in the select).

That's online at https://inbo.github.io/crow/

There's no horizontal (time-related) transitions yet.

**Comment by peterdesmet** [comment]
Ok, I see it. Do you want to keep it?

**Comment by niconoe** [comment]
To me, they're currently fine like they are, I'd just be careful when considering adding others.
