### ISSUE TITLE
Are datetimes in data files in UTC?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#25]
@mrtnrey are the data/timestamps in the data files in UTC? https://crow.weernet.be/bejab/2019/bejab_vpts_20191015.txt

**Comment by niconoe** [comment]
Indeed, I'd like to know this (and also how we want to show the data: UTC or local) for a correct implementation. Bedankt!

**Comment by niconoe** [comment]
@peterdesmet : kind reminder to try to get that info. Thanks!

**Comment by mrtnrey** [comment]
Yes all timestamps are in UTC.

Sorry: I'm not really very active on Github. If you have an urgent question for me, please send it through email, and I'll respond much quicker.

**Comment by mrtnrey** [comment]
You can check it with the fireworks at new years eve: the peak should be centered exactly at 00:00 **local time**.
Now it is shown one hour too early in the graphs.
![peakNewYearsEve](https://user-images.githubusercontent.com/24940236/72436792-9eb2c600-37a1-11ea-9543-182e2a036522.png)

**Comment by peterdesmet** [comment]
Ok, there are two separate things here:

1. Are the datetimes in UTC: yes
2. How should the dates be displayed: @mrtnrey from your comment, I understand local time. That will be addressed in #14.
