### ISSUE TITLE
Make sure the project works with npm

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#26]
For consistency reasons, even if it was initially created with yarn.

**Comment by peterdesmet** [comment]
```
$ yarn serve
-bash: yarn: command not found
```

But it works fine for me using:

```
$ npm install
```

Creates `package-lock.json` which I will commit.

And then:

```
$ npm run serve

Compiled successfully in 6122ms                                                                                                                                 2:15:23 PM

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://10.84.2.68:8080/
```

**Comment by niconoe** [comment]
Excellent. Will try soon to run it on a blank machine, if all works we're already done (I'll update the `README` and remove the yarn.lock.
