### ISSUE TITLE
Improve X axis / time display

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#30]
The x-axis scale is currently a default time axis and could be improved

Peter's suggestion:
- Continue to use identical x-axis for both charts
- Show a big vertical line at (each) midnight on the chart
- Label vertical line (~rotated~ text next to it) with date as `MM DD` (Jan 06)
- Label x-axis below as `HH:MM`
- The number of ticks on x-axis will depend on the time scale, but one every 6 hours seems sufficient

**Comment by peterdesmet** [comment]
Minor update: would first try without rotating the day label next to the vertical line for midnight.

**Comment by niconoe** [comment]
UPDATE: we currently have a simpler format for debugging purposes, that already works ok-ish in my opinion. Still need to implement Peter's suggestion.

**Comment by niconoe** [comment]
@peterdesmet : I implemented your suggestion for the VPIChart (less cluttering problem there, I think). Could you have a look? (it's online at https://inbo.github.io/crow/)

**Comment by peterdesmet** [comment]
Look great!

When switching from radar to UTC, the labels switch to `23:00 UTC`, which looks a bit odd. Would redraw those at 00:00. I assume the midnight bar is then also one for UTC, correct?

**Comment by niconoe** [comment]
Indeed, the bar is drawn at midnight local time, which might be weird in UTC mode :) I can change that!

Another similar doubt I have is for the time period itself: it is centered on the selected date around noon, local time. Should it be centered around noon UTC, if UTC mode is selected? The range would appear a bit nicer in UTC mode, I think.

**Comment by peterdesmet** [comment]
Yeah, would be best if it was centered around UTC noon. Would that require a new load of the data?

**Comment by niconoe** [comment]
Now centered on UTC noon (if UTC mode).

Labels sometimes still appear at 11 hours. Currently D3 choose them automatically, if we decide to force them manually to specific values, I suggest to do that a bit later (once we are 100% confident of the time ranges)
