### ISSUE TITLE
VP chart: altitude 0 is not at the bottom of the chart

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#32]

**Comment by niconoe** [comment]
Implemented (see on https://inbo.github.io/crow/), but I'm not sure in retrospects it's a better representation of the data.

If we look at the very first rectangle, it might give the impression the bottom of the rectangle represents 0 while the top represents 200m. But for what I understand, the whole rectangle actually represents 0m, which might be clearer if the thick appears in the middle of this rectangle.

Opinions?

**Comment by peterdesmet** [comment]
@niconoe I actually quite like it like that. Would only extend the black line of the chart all the way to the top (currently stops at 4800)

**Comment by niconoe** [comment]
@peterdesmet : better like this?

**Comment by peterdesmet** [comment]
Yes.
