### ISSUE TITLE
VP Chart: add altitude scale in feet

### ISSUE THREAD

**Issue by mrtnrey** [inbo/crow#36]
The original (static) VP charts contain an altitude scale in feet, which was explicitly asked for by the Airforce. Can such a scale be added on the right side?
Or, alternatively: a checkbox or radio button to switch between meters and feet.

**Comment by peterdesmet** [comment]
Having the axis on the right side sounds like a good idea

**Comment by niconoe** [comment]
Needs polishing, but a basic version is now visible: https://inbo.github.io/crow/

**Comment by peterdesmet** [comment]
Nice, would make the same number format is used on both (currently `####` vs `##,###`). I think it is fine to use `####`

**Comment by niconoe** [comment]
Done!
