### ISSUE TITLE
Create fetchVpts function

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#4]
Main function `fetchVpts`: from `dateMin`, `dateMax`, `directory` return **combined array of vpts data**.

Helper function `getDates`: from `dateMin`, `dateMax`, `frequency` return array of dates. Only return `yyyy-mm` for months.

Helper function `readVpts`: read single vpts file and set data type:

```js
return {
  datetime: Date.parse(item.datetime), // cast to date
  height: parseInt(item.height), // cast to int
  dd: +item.dd,
  ff: +item.ff,
  dens: +item.dens,
  sd_vvp: +item.sd_vvp
};
```

**Comment by peterdesmet** [comment]
I wonder if the function should return

## Unnested

```js
[
  {datetime: 1472688120000, height: 0, dd: NaN, ff: NaN, dens: NaN, …},
  {datetime: 1472688120000, height: 200, dd: NaN, ff: NaN, dens: NaN, …},
  {datetime: 1472688120000, height: 400, dd: NaN, ff: NaN, dens: 2.8000000000000003, …},
  ...
  {datetime: 1472688120000, height: 4800, dd: NaN, ff: NaN, dens: NaN, …},
  {datetime: 1472688360000, height: 0, dd: NaN, ff: NaN, dens: NaN, …},
  {datetime: 1472688360000, height: 200, dd: NaN, ff: NaN, dens: NaN, …},
  {datetime: 1472688360000, height: 400, dd: NaN, ff: NaN, dens: 5.463636363636364, …},
  ...
]
```

## Nested

```js
[
  {
    key: "1472688120000",
    values: [
      {datetime: 1472688120000, height: 0, dd: NaN, ff: NaN, dens: NaN, …},
      {datetime: 1472688120000, height: 200, dd: NaN, ff: NaN, dens: NaN, …},
      {datetime: 1472688120000, height: 400, dd: NaN, ff: NaN, dens: 2.8000000000000003, …},
      ...
    ]
  },
  {
    key: "1472688360000"
    values: [
      {datetime: 1472688360000, height: 0, dd: NaN, ff: NaN, dens: NaN, …},
      {datetime: 1472688360000, height: 200, dd: NaN, ff: NaN, dens: NaN, …},
      ...
    ]
  },
  ...
}
```

@stijnvanhoey I'm inclined to say unnested, because that is a bit more recognizable. But do our charts require nested data?

**Comment by stijnvanhoey** [comment]
I do think nested is indeed more recognizable although it loses the _multiple heights for a single date_. For the graphics the additional level of nesting is a single `d3` command away, so that not really matters...

**Comment by peterdesmet** [comment]
Wait... 1) I find **un**nested more recognizable and 2) the nested one doesn't remove any info.

**Comment by stijnvanhoey** [comment]
woops, indeed, `unnested`

**Comment by niconoe** [comment]
Not really current anymore since the rewrite.

For info: data is now kept in a nested structure for performance reasons (per timestamp, then height), in the main `Crow` (Vue) component but this object is converted to flat arrays when needed (typically, when passed to chart components) thanks to computed properties.
