### ISSUE TITLE
VP Chart: mimic original FlySafe color scale

### ISSUE THREAD

**Issue by mrtnrey** [inbo/crow#40]
If possible, change the colour scale of the VP chart to the original colour scale.
I know the Airforce people are quite conservative in how they receive information...

![colrscale](https://user-images.githubusercontent.com/24940236/72436400-97d78380-37a0-11ea-8e11-7cff144cfccd.png)

**Comment by peterdesmet** [comment]
Thanks @mrtnrey, this issue is a duplicate of #38

**Comment by niconoe** [comment]
@mrtnrey : as you can see in #38, I'm trying to understand how this scale works (basically: what is the mapping between a given density and a colour) to reimplement it in Crow. Any help or resource (papers?) would be super useful. Thanks!
