### ISSUE TITLE
Do we need a geographic map showing the radar's locations?

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#44]

**Comment by mrtnrey** [comment]
This was not proposed in the original project description of CROW, so nice-to-have but not necessary.
See also current FlySafe map: http://www.flysafe-birdtam.eu/profiles.php

But keep it in the back of your head:
in a later stage, at some point the work for CROW could be applied to the whole ENRAM network.

**Comment by peterdesmet** [comment]
I wonder if at least the radar names should be prepended by the country code for easier selection:

<img width="296" alt="Screenshot 2020-01-27 at 14 48 07" src="https://user-images.githubusercontent.com/600993/73179714-3dc9ad00-4114-11ea-9d33-b77ec94089d0.png">

Or even better, displayed in `<optgroup>`:

<img width="259" alt="Screenshot 2020-01-27 at 14 53 14" src="https://user-images.githubusercontent.com/600993/73180052-cea08880-4114-11ea-839a-0c1ae4d703f5.png">

**Comment by niconoe** [comment]
Last suggestion above by @peterdesmet implemented!

**Comment by peterdesmet** [comment]
Nice! The help text below it is a bit superfluous now. Maybe we can link to the coordinates? In any case, I'm happy @niconoe that you close this issue, and make the help text with coordinates a separate one.

**Comment by niconoe** [comment]
@peterdesmet : do you mean I should change the text such as: "Wideumont is located in Belgium." becomes "Wideumont is located at X, Y"?

**Comment by peterdesmet** [comment]
Yes, indeed. With X, Y maybe a link to Google maps or alike?

**Comment by niconoe** [comment]
Last suggestion implemented. Closing this for now.
