### ISSUE TITLE
Date management improvements

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#47]
The visualisation now allows showing time either as UTC, or as local (to radar) data. However, a few things must be improved for reliability, extensibility and maintenance:

- [x] Allow the user to choose UTC or local in the form (also makes manual testing easier)
- [x] Manually test everything (timelines aligned between charts, correct time in popup, radar data correct with regards to time, sun elevation correct, timezone is correctly selected in winter and summer, ...) => IN PROGRESS
- [x] That might be a good time to refactor time-related code (use Moment.js objects everywhere?), code could be MUCH simpler => IN PROGRESS
- [ ] Investigate automated tests on this topic?

**Comment by peterdesmet** [comment]
For testing, https://jestjs.io/ has been something I wanted to look into. Maybe you can?

**Comment by niconoe** [comment]
Yep, was on my radar too!

**Comment by niconoe** [comment]
Situation is much better now.

**Comment by niconoe** [comment]
Data manual validation:

- [x] axis aligned between charts
- [x] axis show the correct time range, in UTC and local time
- [x] data aligned in VP chart in local time (fireworks at midnight, January 1) 
- [x] data aligned in VP chart in UTC time (fireworks at 23h, December 31) 
- [x] data aligned in VPI chart in local time (fireworks at midnight, January 1) 
- [x] data aligned in VPI chart in UTC time (fireworks at 23h, December 31)
- [ ] TimelineChart: sun elevation is correct in UTC time
- [ ] TimelineChart: sun elevation is correct in local time
- [ ] TimelineChart: night start at the right time (UTC)
- [ ] TimelineChart: night start at the right time (local)

**Comment by niconoe** [comment]
All manual checks now pass and the code is much cleaner/simpler.

This issue can then be considered almost complete, we should just investigate the possibility to automate all those checks, once #56 is unblocked.
