### ISSUE TITLE
Adapt integrateProfile to work with vpts data

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#5]
`integrateProfile()` currently only accepts a single vp and requires a `map` function to work on a vpts:

https://github.com/inbo/crow/blob/20b2d47246ce43530112f867e5e293da58f26c1f/src/main.js#L23-L27

I would wrap that functionality in the function, so we can pass a full vpts data file and get a vpi back, with `mtr` as extra column.

**Comment by niconoe** [comment]
Doesn't really apply to the new architecture anymore.
