### ISSUE TITLE
Decide on css

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#50]
Currently the css borrows (copy/paste) from the oscibio website:

https://github.com/inbo/crow/blob/744612070ad5e1fe7dd163b68e5fdfed9f955300/src/App.vue#L41-L70

It would be good if we can actually import oscibio css, but we should also try to make the app a) stand alone (without referencing external css) and b) generic enough so it can be included in multiple website (so no logos).

@niconoe thoughts?

**Comment by niconoe** [comment]
Yep, it's not always easy to see where to draw the line between the common style and the website specific stuff. And CSS is quite limited in terms of abstraction/code reuse. 

At first look, I can think of two approaches, but each has its drawbacks:

1) Manually copy/paste CSS across websites and customisation just like you did. Very simple, works everywhere, but not very reusable.
2) Heavy but more elegant approach: turn the common CSS to SASS or SCSS, keep it in its own repo, and have some mechanism to customise and build variants for different projects. For example via a "variables" file, or a different branch for each website.

I value simplicity over elegance, so I'd go with 1) first, but keep 2) in mind and switch to it if the process becomes tedious or leads to errors in practice.

**Comment by peterdesmet** [comment]
I agree, let's keep it self contained for now and see if we want a generic "oscibio" css repo later.
