### ISSUE TITLE
Not enough pixels to display 96 hours of data

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#51]
@mrtnrey and @peterdesmet:

Q: **Which time ranges (around the selected date at noon) should be available in the final version?** 

We currently have 24 hours (the default), 1 hour (for debugging purposes, will be disabled later) and 96 hours.

The 96 hours interval is causing troubles, because when we show one rectangle (on the heatmap for example) for each 5-minutes period, we lack available pixels on screen. With the current implementation, it has the following impact:

- On the VP Chart, rectangle coordinates (positioning and width, in pixels) are floating point values (such as 1.1256). The browser then does its best to display it, but some rectangles inevitably overlap others, showing incorrect data and visual gaps between rectangles.

- On the timeline, pixel coordinates are rounded to the nearest integer (for smoother visuals). Thus small rectangle width are rounded to 0, and they don't appear.

Possible solutions:

- Get rid of the 96 hours display, if not useful.
- Make graph much larger horizontally (making sure in all cases, we have at least 1 pixel per rectangle)
- other ideas?

**Comment by niconoe** [comment]
@peterdesmet , @mrtnrey : is the 96-hours display actually useful?

**Comment by peterdesmet** [comment]
- 96h*60min/5min would require 1152px
- 72h*60min/5min would require 864px

I notice that the current data width of the charts is 976px, on any screen. I would opt for the 72h hours and reduce the width of the chart to that effect.

**Comment by peterdesmet** [comment]
3 days is the minimum to give context, 1 day should only be used to look at detail.

Ideally, we would be able to show full weeks, to quickly scan larger time series, but that would only work if we aggregate data.

**Comment by mrtnrey** [comment]
Agreed: sometimes it is useful to see the bird migration evolution over longer time.

So I find 72h a bit short. I'd rather opt for the 96h and enlarge the chart. But I can also live with a smaller chart if it is causing too much troubles.

**Comment by niconoe** [comment]
No worries, the chart can be easily extended (at least as a test, then we'll see where we go).

Please note that currently the selected period is doubled (96hrs before and after the selected day), I guess I should change that (so 96h means 48h before and 48h after)? Otherwise the pixel counts given by @peterdesmet would also be twice larger. No technical issue there neither, but I guess it can complicated things from a design/user experience point of view since the chart would be larger than most computer screens.

**Comment by peterdesmet** [comment]
Indeed, the selected period should not be doubled, so 48h before and after when 96h is selected.
