### ISSUE TITLE
Should version (commit number?) be visible in the page

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#57]
That could be nice to answer questions like "what is deployed"?

See an example at https://projects.biodiversity.be/lepidoptera/about/ (bottom of the page)

- From a design standpoint, it should be not too visible
- How to automatically implement that in Vue?

**Comment by peterdesmet** [comment]
If this is easy to implement, that would be cool. I can take care of the design.

**Comment by niconoe** [comment]
@peterdesmet : That's implemented (in the footer, declared in  `App.vue`). Don't hesitate to style!
