### ISSUE TITLE
Profile integration: do we need a threshold on sd_vpp?

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#63]
Question for @mrtnrey (tell me if you're not the right person for this!)

While revisiting the old profile integration code, I notice we set a (configurable, with a default of 2) threshold for sd_vpp values. I'm trying to simplify things, so I was wondering if this was useful/needed for CROW. 

Subsequent questions: if yes, if the current value (2) is correct? Or should it be configurable in the interface? Or inferred from the data (there's a comment in this sense, but I don't know how).

Thanks!

Note to self: the (poorly managed) NaN values returned after filtering might be the source of #59 and #21. Removing the filtering code would also simplify types.

**Comment by peterdesmet** [comment]
@adokter what is the purpose of sd_vpp_threshold and do we need to keep this as an option in a javascript function to integrate profiles?

**Comment by adokter** [comment]
Yes - it is currently the only threshold by which insects and birds are distinguished. The default 2m/s is typically fine, but good to keep the flexibility of changing it.

**Comment by niconoe** [comment]
Perfect, thanks, we'll keep it in the function for flexibility.

@mrtnrey : Do you want the end user to be able to change this threshold and see the effect on the graph, or should that parameter be kept hidden from users?

**Comment by peterdesmet** [comment]
I would definitely keep that hidden.
