### ISSUE TITLE
How to show missing values (integrated data)

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#64]
It appears that in some cases, we have no integrated value (MTR, VPI, ...) for a given time, despite having radar data. This happens if the source data at the time has sd_vvp values below 2, and therefore considered as the echo from insects and not birds (see #63).

**Question**: how should we represent that missing data on the VPI chart line? I see two options:

1) show the value as 0 (point appear on the bottom axis)
2) skip the point entirely, the line joins the previous time period to the next one.

The former can make sense because it shows "no birds at the time", the later can make sense because it shows "no integrated data at the time".

**Comment by peterdesmet** [comment]
I agree: second option. @adokter, is this also how this is done at bioRad?

**Comment by adokter** [comment]
Strictly the algorithm says there are no birds if sd_vvp is below 2 in all height layers, so I would opt for option 1. This happens often during the day, when there are lots of insect echoes in the sky.

But if you have jittery behaviour of the threshold during the night, you might want to evaluate if a slightly lower value works better. Good rule of thumb is that daytime echoes should be reliably removed, while in peak migration periods (Sep-Oct, Apr-May) the sd_vvp threshold should not interfere much during the night.

**Comment by niconoe** [comment]
Thanks @adokter, those kind of comments are super insightful for dummies like me :)

I guess this "no birds -> show 0" logic applies to all the integrated values (MTR ,RTR, VID, ...)

**Comment by niconoe** [comment]
We have option 1) for now. Please reopen if needed.
