### ISSUE TITLE
Streamline layout of popups

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#66]
The chart and timeline now both have a popup (never shown at the same time):

<img width="261" alt="popups" src="https://user-images.githubusercontent.com/600993/75337583-8e583580-588d-11ea-81e5-0f32dd673013.png">

I would:

- [x] Update title to `Feb 24 - 07:25 CET` (or UTC if so selected)
- [x] Text in body of popup: not bold
- [ ] Place `Period: twilight` on a new line

**Comment by niconoe** [comment]
Parking this for a while since for some weird bug (not sure if it's my code, in Boostrap-Vue, ...) I currently can't place HTML (br tag) anymore inside popups. Will revisit later.

**Comment by niconoe** [comment]
Update: implemented a temporary workaround: 
![Screenshot 2020-03-06 at 11 17 53](https://user-images.githubusercontent.com/386387/76074870-51cabf00-5f9c-11ea-9a0b-a1416f4c5b58.png)
