### ISSUE TITLE
Make "searches" sharable via URLs

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#68]
- All form fields are bind to URL parameters (so Crow take them into account)
- We generate a copy-pastable URLs (permalinks) the reflect the current state of the form. People can bookmark or share this URL.

**Comment by niconoe** [comment]
@peterdesmet : on https://inbo.github.io//crow, you'll see there's now a "copy URL" button that can be used to get a (shareable) URL directly in the clipboard. For the moment only the "radar" parameter is taken into account, but obviously the idea is to make it work for all form fields.

Can you validate the concept? If you like it, I'll continue further (implement all form fields and probably refactor).

**Comment by peterdesmet** [comment]
A button is nice, but requires a bit more explanation to the user. I guess it is easier to implement than have the url change on interaction with the form?

Also, I noticed a default `#/` is added to the url: is that an artefact of this implementation?

**Comment by niconoe** [comment]
Indeed. I was initially trying to change the URL directly in the bar, but it goes a bit against the flow of Vue in Single Page Application mode and things become quickly messy (they use hacks and advanced features to allow to have the illusion of multiple pages - including history, backward button, ... - while the page is actually never reloaded). That's why I added the button, I think it's quite a common pattern for that kind of stuff. I can try again/investigate further if this points bother you.

About the `#/`: I can configure Vue-router in a different mode to use standard URLs. We'll lose IE9 support (I can live with that, and not sure the rest works with it, anyway), but we'll also have to make sure it works on GitHub pages (see https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations and https://stackoverflow.com/questions/47677220/vuejs-history-mode-with-github-gitlab-pages).

**Comment by peterdesmet** [comment]
Ok, button is good. Once you have the full url, I'll try to position it somewhere good.

The `#/`: if it's difficult to get rid of it, it's fine to leave it.

**Comment by peterdesmet** [comment]
Ok, button is good. Once you have the full url, I'll try to position it somewhere good.

The `#/`: if it's difficult to get rid of it, it's fine to leave it.

**Comment by niconoe** [comment]
@peterdesmet: yep, I tried to make this work without the `#`, but it was becoming a pile of hacks (and still not working), so I'm parking that for now.

**Comment by niconoe** [comment]
Reopening so I remember to implement the other parameters.

**Comment by peterdesmet** [comment]
Ok, now worries. Notify me here if I can style the button.

**Comment by peterdesmet** [comment]
Nice! Yes, I would also include those parameters, so the exact view can be shared.

**Comment by niconoe** [comment]
@peterdesmet: the button is now in working condition, don't hesitate to style!
