### ISSUE TITLE
Update vpts x-axis labels to the ones from vpi

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#69]
The vpts x-axis labels still have @ signs. Can this be updated to the VPI format?

**Comment by niconoe** [comment]
Sure! Should I also try adding the vertical lines at (each) midnight so we evaluate if it works for this chart too?

**Comment by peterdesmet** [comment]
Yes, would be very cool to have the vertical lines for this chart too!

**Comment by niconoe** [comment]
Update: refactored code so the vertical lines are now managed by a dedicated component.

**Comment by niconoe** [comment]
Now implemented!
