### ISSUE TITLE
CROW colour scheme

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#70]
- [x] Keep as an option next to bioRad
- [x] Maybe rename to the original colour scale name?
- [ ] Choose a lighter gray as "no data" colour
- [ ] Maybe choose a fixed colour scheme (one value = one colour), rather than having it be applied to the available data range

**Comment by niconoe** [comment]
@peterdesmet: initial crow (=red-ish) color scheme was remove, and replaced by Viridis. Can I close this issue?

**Comment by peterdesmet** [comment]
Ok, but there are some additional improvements to be done (either as part of this issue or separately), namely that the overhead and text for viridis should be white, since the current dark gray is not readable:

<img width="102" alt="Screenshot 2020-05-13 at 13 09 22" src="https://user-images.githubusercontent.com/600993/81805401-12c86500-951b-11ea-8381-f1c1bb7aa4ca.png">

**Comment by niconoe** [comment]
Change implemented for Viridis!
