### ISSUE TITLE
app malfunctioning in Microsoft Edge

### ISSUE THREAD

**Issue by mrtnrey** [inbo/crow#79]
There seems to be a problem with the app in Microsoft Edge, reported by Peter Bellen (Aviation Safety Directorate Belgian Airforce):

> Opmerking bij Crow. Indien je een radar selecteert vb Herwijnen en juist daarvoor heb je Wideumont geselecteerd krijg je de data grafiek van Wideumont, klik je dan op de radar van vb Jabbeke krijg je de gegevens van Herwijnen. Je krijgt nooit de gegevens te zien van de radar die je aanklikt maar wel die van de vorige aangeklikte radar. 

Browser & OS: Microsoft Edge on Windows 10

**Comment by niconoe** [comment]
Thanks for the report @mrtnrey, I'll investigate that soon.

**Comment by mrtnrey** [comment]
I could not reproduce the User Story reported above (on a Acer Swift running Win 10 and MS Edge): the app functioned as expected.

**Comment by niconoe** [comment]
Good to know, I'll try too (just to make sure we can close this)

**Comment by niconoe** [comment]
Hmmm, I can indeed reproduce the issue with Edge up-to-date (86.0.622.38) on my Win 10 pro laptop. I also confirmed within the browser inspector that the "previous" data file is indeed loaded.

Note to self: did some Google search for that, nothing obvious yet. We might try to replace the `change` event on b-form, by b-input, but those two events are not documented in BootstrapVue doc... weird.

**Comment by niconoe** [comment]
We might also try the `debounce`: https://bootstrap-vue.org/docs/components/form-input
