### ISSUE TITLE
Document data flow

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#81]
I think it would be useful to document the data flow for interested developers:

1. Input data file (link to example)

```
code block with literal ascii data
```

2. Is read by `function_x()`, output is:

```
json object (3 lines)
```

3. Integrated with `function_y()`, output is:

```
json object (3 lines)
```

4. This is passed to `chart_x()`

**Comment by niconoe** [comment]
Decision meeting: keep it simple and move it to README.

**Comment by peterdesmet** [comment]
Reviewed and updated.
