### ISSUE TITLE
Add more explanation to site

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#83]
The site is now functional (https://inbo.github.io/crow/#/), but the user does not get much guidance. Would be good to write some explanation.

**Comment by niconoe** [comment]
In today's meeting, it has been decided @mrtnrey will write a short description to be placed at the top of the page.

**Comment by mrtnrey** [comment]
I have written a very short guidance, currently in Eng. and Nl.
@niconoe : are you native French speaking, and could you translate this bit of text for the Fr. version? Tnx!

[CROW CONTENT ENG short.pdf](https://github.com/inbo/crow/files/5607840/CROW.CONTENT.ENG.short.pdf)
[CROW CONTENT NL short.pdf](https://github.com/inbo/crow/files/5607842/CROW.CONTENT.NL.short.pdf)

**Comment by niconoe** [comment]
@mrtnrey: sure, no problem for a Fr version. I'll look into that soon!

**Comment by peterdesmet** [comment]
Note that I have updated the intro text + chart explanation! See the live website for the current version

**Comment by mrtnrey** [comment]
Cool! The UX is much better with the new design. Thank you both!

However, I think the top text is still a bit lost + 4 different font sizes. How could we improve this?
Suggestion: keep only the title + number of birds, and moving the rest of the introductory text into a collapsing element (info icon or similar)?

**Comment by peterdesmet** [comment]
@mrtnrey thanks for the feedback. I quite like the introduction. It's easy to read the first time you visit, and then ignore the second (scrolling down if need be). But yes, 4 font sizes is maybe too much: is it better if we just include the note in the paragraph?

![587c18de-e461-4a7d-b08b-167c53e818ba](https://user-images.githubusercontent.com/600993/100894636-fd1d8b80-34bc-11eb-926b-23fade9a958c.png)

**Comment by peterdesmet** [comment]
I think this issue can be closed.
