### ISSUE TITLE
Implement possibility to translate text

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#85]

**Comment by niconoe** [comment]
Note to self: I briefly explored options to integrate gettext via multiple packages, but I think for this very simple use-case (a few static strings to translate), we'll probably be better with a minimalistic custom solutions (per-language string in computed values, or something similar). That'll make us avoid maintenance hell.

**Comment by niconoe** [comment]
@peterdesmet : wasn't that also for milestone 1?

**Comment by peterdesmet** [comment]
Sure, will add! Easy custom solution is fine by me.

**Comment by niconoe** [comment]
@peterdesmet: where/how would you like to see the language selector?

For the moment, I imagine 3 simple links arranged horizontally (English - Nederlands - Français), somewhere around the top-right of the page (aligned with the main title?)

**Comment by peterdesmet** [comment]
Yes, what you suggest is ok. We could bring the navbar back if needed.

**Comment by niconoe** [comment]
Basic selector (+use example) in place, next steps:

- restructure components so the selector can be placed at the top of the page (but not in `App`)
- implement a good mechanism for more complex and dynamic strings
- implement in components, translate strings in FR and NL

**Comment by niconoe** [comment]
Update: the mechanism is there, next steps are:

1) Update various components so the fixed strings are extracted in a specific data structure and are using our mechanism
2) Update all strings in that data structure in NL and FR (I can handle FR).

Before that, I'd like to have confirmation that we are (mostly) happy with the current status of the English texts and strings. No need for perfection, but if we plan large changes, it's easier to do them better. @peterdesmet? @mrtnrey?

**Comment by peterdesmet** [comment]
👍 I have reviewed the English text on the site in November. Only the footer will undergo some change.

**Comment by niconoe** [comment]
Good progress is being made. Let's close this issue and open new ones for specific questions and issues about this feature.
