### ISSUE TITLE
Add Den Helder radar

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#86]
> Can you add the other Dutch radar too, Den Helder? I’m using your CROW tool quite often, since it’s updated more often each hour.

_Originally posted by @hvangasteren in https://github.com/inbo/crow/issues/76#issuecomment-715287093_

**Comment by peterdesmet** [comment]
Hi @hvangasteren, cool that you are already using the CROW tool!

I'll let @mrtnrey answer if there is a possibility to add the NL Den Helder radar.

**Comment by mrtnrey** [comment]
We (KMI) only receive Herwijnen from KNMI, so adding Den Helder is not possible right now, sorry.
The vol2bird docker is taking all available radars we currently receive.

**Comment by hvangasteren** [comment]
So If I ask KNMI to forward Den Helder too, this will automatically be added J

Thanks

Hans

**Comment by mrtnrey** [comment]
Well, not automatically, but I could add it, yes.

Files from NLDHL will be very similar to NLHRW, so I expect this would be quite easy.

**Comment by niconoe** [comment]
@mrtnrey : cool, just tell me when the files are on the server and I'll update CROW!

**Comment by mrtnrey** [comment]
🥳 
Den Helder is added to https://opendata.meteo.be/ftp/observations/radar/vbird/

**Comment by niconoe** [comment]
Thanks, it's been added! 

(data is only available from today - oct 29)

**Comment by hvangasteren** [comment]
Thanks all!

 

Now I can use this website instead of Flysafe … J

Best regards,

Hans
