### ISSUE TITLE
Misplaced daily lines

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#87]
![Screenshot 2020-10-27 at 15 33 57](https://user-images.githubusercontent.com/386387/97316427-025a3b80-186a-11eb-8c58-20778ab36f41.png)

**Comment by niconoe** [comment]
It appears the daily line is in fact correctly placed (relative to the data), but that the chart itself is shifted (data start at 01:00am instead of midnight). 

Problems seems limited to "radar timezone" mode, and only in winter time.

**Comment by niconoe** [comment]
Okay, the problem only appears AROUND daylight saving time changes (when UTC offset is different at selected date and at charts first day).

Simple way to solve that might be to keep the chart as it is, but avoid drawing the day line if it falls outside of the chart :)

**Comment by peterdesmet** [comment]
Fine solution.
