### ISSUE TITLE
Allow radars to be selected from map with points

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#90]
In addition to the current (list) selector.

Should be integrated in selection area, maybe allow to collapse

**Comment by niconoe** [comment]
Will probably need some visual improvements so it doesn't take too much space above the charts, but it's now implemented (see https://inbo.github.io/crow/#/)

I had great fun with this one :)

**Comment by peterdesmet** [comment]
Implementation is great, with correct interaction between map and dropdown. I think at this point it is not necessary to add outlines of neighbouring countries.
