### ISSUE TITLE
Documentation/architecture: how to customise index.html

### ISSUE THREAD

**Issue by niconoe** [inbo/crow#95]
This has been discussed in the context of Google Analytics (that KMI/IRM may want to implement).

Everything is compiled by Vue-CLI so far. 

Important related concern for the future: how to manage codebases (one generic version + one "customized" for KMI). Do we really need two codebases that evolve in parallel? If so, should we split the codebase between reusables VS non-reusable components?

**Comment by niconoe** [comment]
As a first step, I suggest the following approach:

- We keep a single GitHub repository
- The `master` branch holds the generic version (stable and deployable at all time: features and large bugfixes happen in feature branches)
- KMI's custom version happens in a different branch (merge from `master` regularly)
- KMI embraces the `Vue-CLI` workflow: the source tree is updated then compiled via `npm build`(rather than manually hack compiled HTML pages)

I think it's a decent solution to keep things simple and sane, but it would be great to have KMI's team (in charge of customisation/maintenance ) opinion. @mrtnrey?

**Comment by mrtnrey** [comment]
@niconoe @peterdesmet  We have a first deployment on meteo.be !

https://www.meteo.be/birddetection/

**Comment by mrtnrey** [comment]
Just for completeness (see also #111):

Our final deployment will be on https://www.meteo.be/services/birdDetection/

And three aliases will be defined like this:
https://www.meteo.be/birddetection to https://www.meteo.be/services/birdDetection/?lang=en
https://www.meteo.be/vogeldetectie to https://www.meteo.be/services/birdDetection/?lang=nl
https://www.meteo.be/detectiondoiseaux to https://www.meteo.be/services/birdDetection/?lang=fr
