### ISSUE TITLE
Lower resolution

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#96]
The temporal resolution of the radars seem to be 5 min. I'm curious:

- [x] If the charts would still look ok if we only draw the data for every 10 minutes (comparative screenshot)
- [x] If that would allow us to reduce the width of the charts
- [x] If it would be possible to reduce calculation time (skipping ahead to the next 10 minutes), improving performance
- [x] If it would be possible to download the data at a 10 minute resolution (skipping rows, would have to be a setting per radar, as not all radars use 5 min resolutions), improving performance **no**

**Comment by peterdesmet** [comment]
If we decide to use smaller width chart, we can probably use `container-xl` (`<b-container fluid="xl">`) to stop the container from extended on large screens (#97). Currently, `container-xl` is still to small to capture the full width of the charts.

**Comment by niconoe** [comment]
@peterdesmet: I can prototype that in a branch, but not sure exactly how easy that'll be (multiple assumptions in code that resolution is 5 minutes, I'm afraid). I can already give some suppositions:

> If the charts would still look ok if we only draw the data for every 10 minutes

I guess so, to try

> If that would allow us to reduce the width of the charts

I think we fined-tuned the size based the resolution, so halving the width of the charts should be easily doable. Something intermediate (between the current width and the half-width) might be more difficult: in the past, we often encountered visual artefacts (white space between data blocks in VP chart) with certain interval and monitors (Retina or not, for example). Hence the choice of the current values.

> If it would be possible to reduce calculation time (skipping ahead to the next 10 minutes), improving performance

I think so. At least the memory burden could be (roughly) halved, and the drawing (and related calculations, were most time is spent) should also be better.

>  If it would be possible to download the data at a 10 minute resolution (skipping rows, would have to be a setting per radar, as not all radars use 5 min resolutions), improving performance

The download itself would be the same, filtering would happen afterwards by skipping rows before they are saved to our  data structures. So, not much gain here.

**Comment by peterdesmet** [comment]
> multiple assumptions in code that resolution is 5 minutes, I'm afraid

Making this more generic will probably introduce complexity, but I guess it must be done if we want to try this lower resolution? It would be good for GloBAM though, where much of the data is not coming in at 5 minutes, but 10 or 15 minutes.

**Comment by niconoe** [comment]
@peterdesmet: Done, CROW doesn't assume anymore that data resolution = displayed resolution. The [test version online](https://inbo.github.io/crow/#/) now uses a 10 minutes resolution, please test. 

Comments:

1. seems indeed lighter/faster on the browser
2. I didn't reduced the charts width so far (tell me if you want to me to try things there, or try this by yourself)
3. you can play with the app resolution yourself (see `appTemporalResolution` in `config.ts`)
4. some related features that are relatively simple to implement (for GloBAM) but not done yet because out of scope for CROW: 
    - upsampling (data resolution lower than displayed resolution)
    - data resolution configured per radar and not globally (so the same CROW instance can show several radars with different data resolutions)

**Comment by mrtnrey** [comment]
I also have the impression that the webapp load faster indeed.
Still we have to check the validity of the numbers/colours shown ( = #45 )

**Comment by peterdesmet** [comment]
The width of the charts has been reduced too, so it shows more comfortably on smaller screens.

**Comment by niconoe** [comment]
@mrtnrey : indeed we still need to check the validity of number / colors. What I did when implementing this lower resolution change is comparing the result before / after. So we're still unsure about the inital situation, but at least we can say this change doesn't make the situation worse :)
