### ISSUE TITLE
Rework layout to fit introduction and selection map

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#97]
Rework the layout of the application to fit in an introduction text, a summary stat for Belgium and a map to select radars. Must also scale down nicely on small screens.

**Comment by peterdesmet** [comment]
Favourite attempt so far:

- Remove navbar
- Explanatory title "Weather radars can detect bird migration"
- Summary stat is first sentence in introduction, not something separate
- Introduction uses `container` to keep it readable
- Select and chart area use `container-fluid` (= full width)
- Select area is dark, chart area lighter, both create some separation from the introduction (white background)
- Select area is vertical left on big screens, horizontal top on small screens
- Radar map (which is square) is not visible in horizontal bar on small screens, but select box is still there
- Radar map is last element (to not break up elements too much), so time component is now first element
- First chart can be seen on most screens
- Share button still needs to be added back (not sure yet where)

Large screen:

![crow_8](https://user-images.githubusercontent.com/600993/100437218-be449b80-30a0-11eb-9e9c-4495bb4822d0.png)

Small screen:

![crow_8_sm](https://user-images.githubusercontent.com/600993/100437257-cb618a80-30a0-11eb-80e1-9dc91e5cddbe.png)

**Comment by peterdesmet** [comment]
Feedback welcome!

**Comment by mrtnrey** [comment]
See https://github.com/inbo/crow/issues/83 for some input for the description.

**Comment by niconoe** [comment]
Thanks @peterdesmet.

As said in the PR, I really like this new layout and consider it a big improvement.

I'm wondering if a bit more space between the intro and the app itself wouldn't be even better, especially on very large screens where everything appears a bit stuck in the top left:

![Screenshot 2020-12-01 at 09 46 22](https://user-images.githubusercontent.com/386387/100717663-a4fe6080-33ba-11eb-916b-ec614c754fa0.png)

**Comment by peterdesmet** [comment]
- [ ] Add margin on large screens
- [ ] Center map
- [ ] Center in fluid-container?

@niconoe will do. Centering content in the container-fluid on giant screens is not something I'm familiar with in Bootstrap

**Comment by peterdesmet** [comment]
Regarding fluid-container, there is a [method](https://bootstrap-vue.org/docs/components/layout) for that, see https://github.com/inbo/crow/issues/96#issuecomment-736415826, but it currently doesn't contain the full width of the chart, so I extended that maximum width with css (4bbc6c3)

**Comment by niconoe** [comment]
The recent changes look great on 3 different screens here (see large screenshot below), so I think we can close this one.

![Screenshot 2020-12-01 at 12 15 44](https://user-images.githubusercontent.com/386387/100734134-79d23c00-33cf-11eb-8b2f-56a74178b7e5.png)

**Comment by mrtnrey** [comment]
Sorry to open this one again, but is it possible to add the borders of the neighbouring countries? I see it is an svg so it might not take too long to change this? Currently I still miss some geographic reference of the radar locations.

**Comment by peterdesmet** [comment]
@mrtnrey makes sense, added as separate issue in https://github.com/inbo/crow/issues/110
