### ISSUE TITLE
Add information, partners to footer

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#99]
Use information included in #83

**Comment by niconoe** [comment]
@peterdesmet: is this for milestone 1? Or do you think this should be handled by KMI in the "adapted" (derived from generic) CROW version?

**Comment by peterdesmet** [comment]
I will try to tackle this on Monday for milestone 1. Even for the generic version we have to indicate the partners.

**Comment by peterdesmet** [comment]
Blocked by #105

**Comment by peterdesmet** [comment]
@mrtnrey I have reworked the text you provided into a footer that now looks like this (not live yet in the website):

<img width="1032" alt="Screenshot 2021-01-25 at 16 18 18" src="https://user-images.githubusercontent.com/600993/105725208-f5acb880-5f28-11eb-9ba5-229fa0ede46b.png">

- I rephrased some of the text
- I shorted the references
- I listed the radar operators as "Radar data provided by" and added KMI as well
- I only included the logos of the main partners + Belspo

@mrtnrey let me know if his looks good or if you want to rephrase some things before I start translating.

**Comment by mrtnrey** [comment]
For me the footer is already very nice! Maybe some suggestions:
- text can be maybe in a smaller fontsize (to be tested)
- After the sentence "The bird detection is based on the algorithm described in Dokter et al. (2011, 2019)." we could add sentence with a link to the open data repository: "Raw data files are accessible via [RMI open data portal.](https://opendata.meteo.be/ftp/observations/radar/vbird/)"
- Maybe it's needed to adapt the logos to the language. For INBO and RMI we have logos that differ ("RMI"/"KMI"/"IRM")

**Comment by peterdesmet** [comment]
@mrtnrey, this is how it looks with a smaller font:

<img width="1051" alt="Screenshot 2021-01-29 at 14 15 40" src="https://user-images.githubusercontent.com/600993/106279390-a7572c80-623c-11eb-9045-6d8d7e063261.png">

**Comment by peterdesmet** [comment]
- Smaller font: the same for me, @mrtnrey you can choose based on the screenshot above
- I have added the sentence as "Raw data are accessible via the RMI open data portal."
- I would keep the logos simple and not change them based on the language, the institutions are already named by their other name in the text.

**Comment by peterdesmet** [comment]
Correction, I used "source data" rather than "raw data":

> The source data are accessible via the RMI open data portal.

**Comment by mrtnrey** [comment]
Source data is also fine. I think I prefer the smaller font size.

If the logos are the same for all languages, then our bilingual logo should be used. Can you replace the "RMI"-logo with the one attached? Tnx!

![KMI_IRM](https://user-images.githubusercontent.com/24940236/106594807-eb0aa880-6552-11eb-907e-d70f5b265ea4.png)
[KMI_IRM.svg.zip](https://github.com/inbo/crow/files/5910807/KMI_IRM.svg.zip)

**Comment by peterdesmet** [comment]
Thanks, but the attached svg doesn't seem to be an encoded png file? Should I just use the screenshot png?

**Comment by peterdesmet** [comment]
I have updated the footer with small text and new (png) logo:

<img width="969" alt="Screenshot 2021-02-02 at 13 33 45" src="https://user-images.githubusercontent.com/600993/106600918-5193c480-655b-11eb-840c-9061f293120e.png">

I think this can be closed now

**Comment by mrtnrey** [comment]
Very nice, thanks. There might be a problem with the svg indeed (I didn't check beforehand) but it is already solved I see.
